// authui.c
// Generated by decompiling authui.dll
// using Reko decompiler version 0.7.1.0.

#include "authui.h"

Eq_4 g_tFFFFFFFF;
Eq_4 g_t0002;
Eq_2322 g_t10000000 = 
	{
		0x5A4D,
		0x000000F0,
	};
Eq_2260 g_t10001088 = 
	{
		&g_dw100240E8,
		&g_dw10024138,
	};
Eq_4366 g_a10001A70[] = 
	{
	};
Eq_4365 g_a10001A74[] = 
	{
	};
Eq_585 g_t10001AF4 = 
	{
		0x10008D70,
		0x10008D30,
	};
word32 g_dw100020C8 = 0x00000000;
word32 g_dw100020D4 = 0x00000000;
word32 g_a100071A4[] = 
	{
	};
<anonymous> g_t100096A0 = <code>;
struct Eq_83 * g_ptr1001F20C = null;
struct Eq_937 * g_ptr10024000 = &g_ptr10024000;
word32 g_dw10024008 = 0x00000000;
word16 * g_ptr1002400C = &g_w100070F2;
word32 g_dw10024020 = 0x00000000;
word32 g_dw10024024 = 0x00000000;
ui32 g_dw10024028 = 0x00000000;
ui32 g_dw1002402C = 0x00000000;
ui32 g_dw10024068 = 0x00000000;
ui32 g_dw1002406C = 0x00000000;
uint32 g_dw100240C0 = 0xFFFFFFFF;
ui32 g_dw100240C4 = 0xBB40E64E;
ui32 g_dw100240C8 = 0x44BF19B1;
word32 g_dw100240CC = 0x80000000;
Eq_570 g_t100240D0 = 0xFFFFFFFF;
int32 g_dw100240E0 = 0;
word32 g_dw100240E4 = 0x00000000;
word32 g_dw100240E8 = 0x00000000;
word32 g_dw100240EC = 0x00000000;
struct Eq_5 * g_ptr100240F4 = null;
word32 g_dw100240F8 = 0x00000000;
word32 g_dw100240FC = 0x00000000;
ui32 g_dw10024100 = 0x00000000;
ui32 g_dw10024104 = 0x00000000;
word32 g_dw10024138 = 0x00000000;
struct Eq_2214 * g_ptr100241C4 = null;
struct Eq_2211 * g_ptr100241C8 = null;
struct Eq_6 * g_ptr100241CC = null;
struct Eq_7 * g_ptr100241D0 = null;
ptr32 g_ptr100241D4 = 0x00000000;
Eq_258 g_t100241D8 = 
	{
		null
	};
struct Eq_4 * g_ptr100241DC = null;
struct Eq_4 * g_ptr100241E0 = null;
ui32 g_dw100241E4 = 0x00000000;
Eq_258 g_t100241E8 = 
	{
		null
	};
struct Eq_5 * g_ptr100241EC = null;
struct Eq_5 * g_ptr100241F0 = null;
struct Eq_2204 * g_ptr100241F4 = null;
Eq_2220 g_t100241F8 = 
	{
		0x00
	};
ptr32 g_ptr100241FC = 0x00000000;
struct Eq_2201 * g_ptr10024200 = null;
struct _RTL_CRITICAL_SECTION g_t10024420 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00000000,
	};
Eq_569 g_t1002443C = null;
word32 g_dw10024440 = 0x00000000;
word32 g_dw10024444 = 0x00000000;
ui32 g_dw1002444C = 0x00000000;
struct Eq_4 * g_ptr10024454 = null;
struct Eq_4 * g_ptr10024458 = null;
word32 g_dw1002445C = 0x00000000;
word32 g_dw10024460 = 0x00000000;
word32 g_dw10024464 = 0x00000000;
ptr32 g_ptr10024468 = 0x00000000;
Eq_842 g_t10024480 = null;
ptr32 g_ptr10024484 = 0x00000000;
struct _RTL_CRITICAL_SECTION g_t100244C8 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00000000,
	};
ptr32 g_ptr100244E0 = 0x00000000;
word32 g_dw100244F0 = 0x00000000;
word32 g_dw100244F8 = 0x00000000;
word32 g_dw100244FC = 0x00000000;
ptr32 g_ptr10024508 = 0x00000000;
word32 g_dw10024518 = 0x00000000;
word32 g_dw10024520 = 0x00000000;
word32 g_dw10024524 = 0x00000000;
ptr32 g_ptr10024530 = 0x00000000;
word32 g_dw10024540 = 0x00000000;
word32 g_dw10024548 = 0x00000000;
word32 g_dw1002454C = 0x00000000;
ptr32 g_ptr10024558 = 0x00000000;
word32 g_dw10024568 = 0x00000000;
word32 g_dw10024570 = 0x00000000;
word32 g_dw10024574 = 0x00000000;
ptr32 g_ptr10024580 = 0x00000000;
word32 g_dw10024590 = 0x00000000;
word32 g_dw10024598 = 0x00000000;
word32 g_dw1002459C = 0x00000000;
word32 g_dw100245A8 = 0x00000000;
word32 g_dw100245B8 = 0x00000000;
word32 g_dw100245C0 = 0x00000000;
word32 g_dw100245C4 = 0x00000000;
ptr32 g_ptr100245D0 = 0x00000000;
ptr32 g_ptr100245D4 = 0x00000000;
ptr32 g_ptr100245D8 = 0x00000000;
ptr32 g_ptr100245DC = 0x00000000;
ptr32 g_ptr100245E0 = 0x00000000;
ptr32 g_ptr100245E4 = 0x00000000;
int32 g_dw10024618 = 0;
ptr32 g_ptr1002461C = 0x00000000;
word32 g_dw10024624 = 0x00000000;
Eq_842 g_t10024664 = null;
int32 g_dw10024668 = 0;
<anonymous> * g_ptr10025410 = &g_t10009B40;
word16 g_w100070F2 = 0x004B;
<anonymous> g_t10009B40 = <code>;

