// certCredProvider.c
// Generated by decompiling certCredProvider.dll
// using Reko decompiler version 0.7.1.0.

#include "certCredProvider.h"

// 10002AE0: void DllGetClassObject(Register word32 ebx, Register word32 ebp, Register word32 edi, Register selector es, Register selector ds, Stack word32 dwArg04)
void DllGetClassObject(word32 ebx, word32 ebp, word32 edi, selector es, selector ds, word32 dwArg04)
{
	Mem34[fs:0x00:word32] = fp - 0x10;
	word32 ebp_102 = fp - 0x04;
	word32 esp_103 = fp - 0x28;
	word32 eax_279 = dwArg04;
	word32 edx_113 = 0x10001974;
	word32 esi_274 = 0x0C;
l10002B20:
	word32 eax_275;
	word32 ecx_44 = Mem34[edx_113 + 0x00:word32];
	byte cl_45 = (byte) ecx_44;
	if (ecx_44 != Mem34[eax_279 + 0x00:word32])
	{
		byte C_287 = cond(cl_45 - Mem34[eax_279 + 0x00:byte]);
		if (cl_45 == Mem34[eax_279 + 0x00:byte])
		{
			byte cl_298 = Mem34[edx_113 + 0x01:byte];
			C_287 = cond(cl_298 - Mem34[eax_279 + 0x01:byte]);
			if (cl_298 == Mem34[eax_279 + 0x01:byte])
			{
				byte cl_304 = Mem34[edx_113 + 0x02:byte];
				C_287 = cond(cl_304 - Mem34[eax_279 + 0x02:byte]);
				if (cl_304 == Mem34[eax_279 + 0x02:byte])
				{
					byte cl_310 = Mem34[edx_113 + 0x03:byte];
					C_287 = cond(cl_310 - Mem34[eax_279 + 0x03:byte]);
					if (cl_310 == Mem34[eax_279 + 0x03:byte])
						break;
				}
			}
		}
		eax_275 = 0x00 - C_287 | 0x01;
		goto l10002B3E;
	}
	edx_113 = edx_113 + 0x04;
	eax_279 = eax_279 + 0x04;
	esi_274 = esi_274 - 0x04;
	if (esi_274 >=u 0x00)
		goto l10002B20;
	eax_275 = 0x00;
l10002B3E:
	word32 ebx_100;
	if (eax_275 == 0x00)
	{
		word32 ebx_114;
		word32 eax_116 = fn10003880(ebx, esi_274, edi, out edx_113, out ebx_114, out ebp_102);
		Mem119[ebp_102 - 0x14 + 0x00:word32] = eax_116;
		Mem120[ebp_102 - 0x04 + 0x00:word32] = 0x00;
		word32 esi_117 = eax_116;
		esp_103 = fp - 0x28;
		if (eax_116 != 0x00)
		{
			Mem258[eax_116 + 0x00:word32] = 0x10001658;
			Mem259[eax_116 + 0x04:word32] = 0x01;
			__lock();
			Mem261[0x10008498:word32] = Mem259[0x10008498:word32] + 0x01;
		}
		else
			esi_117 = 0x00;
		Mem125[ebp_102 - 0x04 + 0x00:word32] = ~0x00;
		if (esi_117 != 0x00)
		{
			word32 esp_153;
			word32 eax_151;
			word32 esi_147;
			word32 eax_129 = Mem125[esi_117 + 0x00:word32];
			Mem132[fp - 44 + 0x00:word32] = Mem125[ebp_102 + 0x10:word32];
			Mem135[fp - 0x30 + 0x00:word32] = Mem132[ebp_102 + 0x0C:word32];
			word32 edi_136 = Mem135[eax_129 + 0x00:word32];
			Mem138[fp - 0x34 + 0x00:word32] = esi_117;
			if (edi_136 != 0x10002DC0)
			{
				word32 esp_218;
				word32 edi_219;
				word32 ebp_220;
				word32 eax_221;
				selector fs_222;
				byte SCZO_223;
				byte SZO_224;
				byte C_225;
				word32 ebx_226;
				word32 esi_227;
				word32 edx_228;
				word32 ecx_229;
				byte Z_230;
				byte cl_231;
				byte S_232;
				selector es_233;
				selector ds_234;
				Mem138[0x1000919C:word32]();
				word32 edi_236;
				byte SCZO_240;
				byte SZO_241;
				byte C_242;
				word32 ebx_243;
				word32 ecx_246;
				byte Z_247;
				byte cl_248;
				byte S_249;
				edi_219();
			}
			else
			{
				eax_151 = fn10002DC0(edx_113, ebx_114, ebp_102, esi_117, es, ds, dwArg00, dwArg04, dwArg08, out edx_113, out esi_147);
				esp_153 = fp - 0x28;
			}
			word32 eax_155 = Mem138[esi_147 + 0x00:word32];
			word32 esp_156 = esp_153 - 0x04;
			Mem157[esp_156 + 0x00:word32] = esi_147;
			ebx_100 = eax_151;
			word32 edi_158 = Mem157[eax_155 + 0x08:word32];
			if (edi_158 != 0x10002C30)
			{
				word32 esp_179;
				word32 edi_180;
				word32 ebp_181;
				word32 eax_182;
				selector fs_183;
				byte SCZO_184;
				byte SZO_185;
				byte C_186;
				word32 ebx_187;
				word32 esi_188;
				word32 edx_189;
				word32 ecx_190;
				byte Z_191;
				byte cl_192;
				byte S_193;
				selector es_194;
				selector ds_195;
				Mem157[0x1000919C:word32]();
				word32 edi_197;
				word32 eax_199;
				byte SCZO_201;
				byte SZO_202;
				byte C_203;
				word32 esi_205;
				word32 ecx_207;
				byte Z_208;
				byte cl_209;
				byte S_210;
				edi_180();
			}
			else
			{
				fn10002C30(esi_147, dwArg00);
				esp_103 = esp_156 + 0x04;
			}
			if (ebx_100 >= 0x00)
			{
l10002BCB:
				Mem72[fs:0x00:word32] = Mem34[ebp_102 - 0x0C + 0x00:word32];
				word32 esp_74 = esp_103 + 0x04;
				fn10003870(ebx_100, Mem72[ebp_102 - 0x10 + 0x00:word32] ^ ebp_102, edx_113, Mem72[esp_74 + 0x08:word32], ebp_102, Mem72[esp_74 + 0x04:word32], Mem72[esp_74 + 0x00:word32], es, ds, ebp);
				return;
			}
		}
		else
			ebx_100 = 0x8007000E;
	}
	else
		ebx_100 = 0x80040111;
	word32 eax_104 = Mem34[ebp_102 + 0x10:word32];
	if (eax_104 != 0x00)
		Mem108[eax_104 + 0x00:word32] = 0x00;
	goto l10002BCB;
}

// 10002C30: void fn10002C30(Register word32 esi, Stack word32 dwArg04)
void fn10002C30(word32 esi, word32 dwArg04)
{
	__lock();
	Mem15[dwArg04 + 0x04:word32] = __xadd(Mem0[dwArg04 + 0x04:word32], esi | ~0x00);
	if ((esi | ~0x00) == 0x01 && dwArg04 != 0x00)
	{
		Mem35[dwArg04 + 0x00:word32] = 0x10001658;
		__lock();
		Mem37[0x10008498:word32] = Mem35[0x10008498:word32] - 0x01;
		operator delete(dwArg04);
	}
	return;
}

// 10002DC0: Register word32 fn10002DC0(Register word32 edx, Register word32 ebx, Register word32 ebp, Register word32 esi, Register selector es, Register selector ds, Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Register out ptr32 edxOut, Register out ptr32 esiOut)
word32 fn10002DC0(word32 edx, word32 ebx, word32 ebp, word32 esi, selector es, selector ds, word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 & edxOut, ptr32 & esiOut)
{
	*esiOut = esi;
	*edxOut = edx;
	word32 eax_129;
	word32 ebp_116 = fp - 0x04;
	word32 eax_13 = Mem0[0x100080B4:word32] ^ fp - 0x04;
	word32 esp_15 = fp - 0x0C;
	if (dwArg0C == 0x00)
	{
		eax_129 = 0x80070057;
		return fn10003870(eax_129, eax_13 ^ fp - 0x04, edx, ebx, ebp_116, esi, Mem0[esp_15 + 0x00:word32], es, ds, ebp);
	}
	word32 eax_151 = dwArg08;
	word32 edx_150 = 0x10001940;
	word32 esp_114 = fp - 0x10;
	word32 esi_152 = 0x0C;
l10002DF0:
	word32 eax_147;
	word32 ecx_60 = Mem0[edx_150 + 0x00:word32];
	byte cl_61 = (byte) ecx_60;
	if (ecx_60 != Mem0[eax_151 + 0x00:word32])
	{
		byte C_156 = cond(cl_61 - Mem0[eax_151 + 0x00:byte]);
		if (cl_61 == Mem0[eax_151 + 0x00:byte])
		{
			byte cl_167 = Mem0[edx_150 + 0x01:byte];
			C_156 = cond(cl_167 - Mem0[eax_151 + 0x01:byte]);
			if (cl_167 == Mem0[eax_151 + 0x01:byte])
			{
				byte cl_172 = Mem0[edx_150 + 0x02:byte];
				C_156 = cond(cl_172 - Mem0[eax_151 + 0x02:byte]);
				if (cl_172 == Mem0[eax_151 + 0x02:byte])
				{
					byte cl_177 = Mem0[edx_150 + 0x03:byte];
					C_156 = cond(cl_177 - Mem0[eax_151 + 0x03:byte]);
					if (cl_177 == Mem0[eax_151 + 0x03:byte])
						break;
				}
			}
		}
		eax_147 = 0x00 - C_156 | 0x01;
		goto l10002E0A;
	}
	edx_150 = edx_150 + 0x04;
	eax_151 = eax_151 + 0x04;
	esi_152 = esi_152 - 0x04;
	if (esi_152 >=u 0x00)
		goto l10002DF0;
	eax_147 = 0x00;
	if (eax_147 != 0x00)
	{
		word32 eax_135 = fn10004EAB(0x10001960, dwArg08, out edx);
		if (eax_135 == 0x00)
		{
			Mem139[dwArg0C + 0x00:word32] = eax_135;
			eax_129 = 0x80004002;
l10002E29:
			*esiOut = Mem0[esp_114 + 0x00:word32];
			esp_15 = esp_114 + 0x04;
			return fn10003870(eax_129, eax_13 ^ fp - 0x04, edx, ebx, ebp_116, esi, Mem0[esp_15 + 0x00:word32], es, ds, ebp);
		}
	}
	Mem91[dwArg0C + 0x00:word32] = dwArg04;
	word32 esp_99;
	word32 edi_100;
	word32 ebp_101;
	word32 ecx_102;
	word32 eax_103;
	byte SZO_104;
	byte C_105;
	byte Z_106;
	word32 edx_107;
	word32 esi_108;
	word32 ebx_109;
	byte SCZO_110;
	byte cl_111;
	selector es_112;
	selector ds_113;
	Mem91[0x1000919C:word32]();
	word32 edi_115;
	word32 ecx_117;
	word32 eax_118;
	byte SZO_119;
	byte C_120;
	byte Z_121;
	word32 esi_123;
	byte SCZO_125;
	byte cl_126;
	esi_108();
	eax_129 = 0x00;
	goto l10002E29;
}

// 10003100: void fn10003100()
void fn10003100()
{
	word32 esi_13 = Mem0[0x1000800C:word32];
	word32 edi_16 = 0x10008440;
	if (esi_13 != 0x00)
	{
		word32 esp_40 = fp - 0x14;
		do
		{
			word32 ecx_44 = Mem0[edi_16 + 0x00:word32];
			word32 esp_46 = esp_40 - 0x04;
			Mem47[esp_46 + 0x00:word32] = esi_13 + 0x08;
			Mem49[esp_46 - 0x04 + 0x00:word32] = 0x00;
			Mem51[esp_46 - 0x08 + 0x00:word32] = 0x00;
			Mem55[esp_46 - 0x0C + 0x00:word32] = fp - 0x0C;
			Mem57[esp_46 - 0x10 + 0x00:word32] = 0x01;
			Mem59[esp_46 - 0x14 + 0x00:word32] = ecx_44;
			Mem61[esp_46 - 0x18 + 0x00:word32] = esi_13;
			Mem65[esp_46 - 0x1C + 0x00:word32] = 0x10004F30;
			Mem66[esi_13 + 0x20:word32] = ecx_44;
			word32 ebp_69;
			byte SCZO_70;
			word32 esi_71;
			byte SZO_72;
			byte C_73;
			byte Z_74;
			word32 ecx_75;
			word32 eax_76;
			ntdll.dll!EtwRegisterTraceGuidsW();
			esi_13 = Mem66[esi_71 + 0x00:word32];
		} while (esi_13 != 0x00);
	}
	return;
}

// 10003160: Register word32 fn10003160()
word32 fn10003160()
{
	word32 esp_4 = fp - 0x04;
	word32 esi_43 = Mem0[0x1000800C:word32];
	if (esi_43 != 0x1000800C)
	{
		if (esi_43 != 0x00)
		{
			do
			{
				edx = Mem0[esi_43 + 0x08:word32];
				word32 ecx_47 = Mem0[esi_43 + 0x0C:word32];
				word32 eax_48 = edx | ecx_47;
				if (eax_48 != 0x00)
				{
					word32 esp_63 = esp_4 - 0x04;
					Mem64[esp_63 + 0x00:word32] = ecx_47;
					Mem66[esp_63 - 0x04 + 0x00:word32] = edx;
					word32 edi_68;
					byte SCZO_70;
					byte Z_71;
					byte SZO_72;
					byte C_73;
					word32 eax_75;
					word32 ecx_76;
					ntdll.dll!EtwUnregisterTraceGuids();
					Mem77[esi_43 + 0x08:word32] = 0x00;
					Mem78[esi_43 + 0x0C:word32] = 0x00;
				}
				esi_43 = Mem0[esi_43 + 0x00:word32];
			} while (esi_43 != 0x00);
		}
		Mem40[0x1000800C:word32] = 0x1000800C;
	}
	return edx;
}

// 100031B0: void fn100031B0()
void fn100031B0()
{
	Mem2[0x10008458:word32] = 0x00;
	Mem3[0x10008448:word32] = 0x00;
	Mem4[0x10008460:word32] = 0x01;
	Mem5[0x10008464:word32] = 0x00;
	return;
}

// 100031E0: void DllCanUnloadNow()
void DllCanUnloadNow()
{
	if (Mem0[0x10008498:word32] > 0x00)
		return;
	else
		return;
}

// 10003332: Register word32 fn10003332(Register word32 edx, Register word32 ebp, Register selector es, Register selector ds, Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Register out ptr32 edxOut)
word32 fn10003332(word32 edx, word32 ebp, selector es, selector ds, word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 & edxOut)
{
	*edxOut = edx;
	word32 edi_135;
	word32 eax_36;
	word32 ebp_136 = fp - 0x04;
	word32 eax_11 = Mem0[0x100080B4:word32] ^ fp - 0x04;
	word32 esp_125 = fp - 0x24;
	if (dwArg08 != 0x00)
	{
		edi_135 = 0x01;
		if (dwArg08 != 0x01)
			goto l1000351F;
		word32 dwLoc0C_287 = 0x00;
		word32 edx_289 = Mem0[Mem0[fs:0x18:word32] + 0x04:word32];
		while (true)
		{
			__lock();
			word32 eax_297;
			__cmpxchg(Mem0[0x10008428:word32], edx_289, 0x00, out eax_297);
			edx = edx_289;
			*edxOut = edx;
			if (eax_297 == 0x00)
				break;
			if (eax_297 == edx_289)
			{
				dwLoc0C_287 = 0x01;
				break;
			}
			Sleep(1000);
		}
		word32 esp_322;
		word32 esi_316;
		if (Mem0[268469292:word32] != 0x00)
		{
			byte SCZO_412;
			word32 eax_413;
			byte SZO_414;
			byte C_415;
			word32 ebx_416;
			byte Z_418;
			selector fs_419;
			word32 ecx_421;
			amsg_exit();
		}
		else
		{
			Mem428[268469292:word32] = 0x01;
			word32 eax_429 = fn10003813(edx_289, 0x02, fp - 0x04, 0x01, es, ds, 0x10001778, 0x10001780);
			if (eax_429 != 0x00)
			{
l1000344C:
				esp_125 = fp - 0x24;
				eax_36 = 0x00;
				goto l10003521;
			}
			word32 esp_441;
			byte SCZO_444;
			word32 eax_445;
			byte SZO_446;
			byte C_447;
			word32 ebx_448;
			byte Z_450;
			selector fs_451;
			word32 ecx_453;
			initterm();
			Mem458[268469292:word32] = 0x02;
			esp_322 = fp - 0x28;
		}
		esp_125 = esp_322 + 0x04;
		if (dwLoc0C_287 == 0x00)
			Mem405[esi_316 + 0x00:word32] = 0x00;
		if (Mem0[0x10008430:word32] != 0x00)
		{
			Mem350[esp_125 - 0x04 + 0x00:word32] = 0x10008430;
			word32 eax_353 = fn10003920(dwArg00, out edx);
			if (eax_353 != 0x00)
			{
				Mem362[esp_125 - 0x04 + 0x00:word32] = dwArg0C;
				Mem366[esp_125 - 0x08 + 0x00:word32] = 0x02;
				Mem370[esp_125 - 0x0C + 0x00:word32] = dwArg04;
				word32 esp_371;
				word32 edi_372;
				word32 ebp_373;
				byte SCZO_374;
				word32 eax_375;
				byte SZO_376;
				byte C_377;
				word32 ebx_378;
				word32 esi_379;
				byte Z_380;
				selector fs_381;
				word32 edx_382;
				word32 ecx_383;
				selector es_384;
				selector ds_385;
				Mem370[0x1000919C:word32]();
				byte SCZO_389;
				word32 eax_390;
				byte SZO_391;
				byte C_392;
				word32 ebx_393;
				word32 esi_394;
				byte Z_395;
				selector fs_396;
				word32 ecx_398;
				esi_379();
			}
		}
		Mem347[0x100080C8:word32] = Mem0[0x100080C8:word32] + 0x01;
		goto l1000351F;
	}
	else
	{
		word32 eax_95 = Mem0[0x100080C8:word32];
		if (eax_95 > 0x00)
		{
			Mem106[0x100080C8:word32] = eax_95 - 0x01;
			word32 edx_110 = Mem106[Mem106[fs:0x18:word32] + 0x04:word32];
			__lock();
			word32 eax_114;
			__cmpxchg(Mem106[0x10008428:word32], edx_110, 0x00, out eax_114);
			word32 dwLoc0C_109 = 0x00;
			while (true)
			{
				edx = edx_110;
				*edxOut = edx;
				esp_125 = fp - 0x24;
				if (eax_114 == 0x00)
					break;
				if (eax_114 == edx_110)
				{
					dwLoc0C_109 = 0x01;
					break;
				}
				Sleep(1000);
				__lock();
				__cmpxchg(Mem106[0x10008428:word32], edx_110, 0x00, out eax_114);
			}
			if (Mem106[268469292:word32] != 0x02)
			{
				word32 esp_134;
				byte SCZO_137;
				word32 eax_138;
				byte SZO_139;
				byte C_140;
				word32 ebx_141;
				word32 esi_142;
				byte Z_143;
				selector fs_144;
				word32 ecx_146;
				amsg_exit();
				esp_125 = fp - 0x24;
			}
			else
			{
				word32 eax_151 = Mem106[0x10008424:word32];
				word32 dwLoc18_152 = eax_151;
				if (eax_151 != 0x00)
				{
					word32 esi_181 = Mem106[0x10008420:word32];
					word32 dwLoc10_183 = esi_181;
					while (true)
					{
						esi_181 = esi_181 - 0x04;
						if (esi_181 <u eax_151)
							break;
						word32 ecx_203 = Mem106[esi_181 + 0x00:word32];
						if (ecx_203 == 0x00)
							continue;
						Mem208[esi_181 + 0x00:word32] = 0x00;
						word32 esp_209;
						word32 edi_210;
						word32 ebp_211;
						byte SCZO_212;
						word32 eax_213;
						byte SZO_214;
						byte C_215;
						word32 ebx_216;
						word32 esi_217;
						byte Z_218;
						selector fs_219;
						word32 edx_220;
						word32 ecx_221;
						selector es_222;
						selector ds_223;
						Mem208[0x1000919C:word32]();
						word32 edi_225;
						byte SCZO_227;
						word32 eax_228;
						byte SZO_229;
						byte C_230;
						word32 ebx_231;
						byte Z_233;
						selector fs_234;
						word32 edx_235;
						word32 ecx_236;
						ecx_203();
						edx = Mem208[0x10008424:word32];
						*edxOut = edx;
						word32 ecx_240 = Mem208[0x10008420:word32];
						if (edi_225 == edx)
						{
							eax_151 = dwLoc18_152;
							if (dwLoc10_183 == ecx_240)
								continue;
						}
						eax_151 = edx;
						dwLoc10_183 = ecx_240;
						dwLoc18_152 = edx;
						esi_181 = ecx_240;
					}
					word32 esp_253 = esp_125 - 0x04;
					Mem254[esp_253 + 0x00:word32] = eax_151;
					free(Mem254[esp_253 + 0x00:(ptr void)]);
					Mem257[0x10008420:word32] = 0x00;
					Mem260[0x10008424:word32] = 0x00;
					esp_125 = esp_253 + 0x04;
				}
				Mem172[268469292:word32] = 0x00;
				edi_135 = 0x01;
				if (dwLoc0C_109 == 0x00)
					Mem179[0x10008428:word32] = 0x00;
			}
l1000351F:
			eax_36 = edi_135;
l10003521:
			word32 esp_41 = esp_125 + 0x04;
			return fn10003870(eax_36, eax_11 ^ fp - 0x04, edx, Mem0[esp_41 + 0x04:word32], ebp_136, Mem0[esp_41 + 0x00:word32], Mem0[esp_125 + 0x00:word32], es, ds, ebp);
		}
		goto l1000344C;
	}
}

// 10003540: Register BOOL DllMain(Stack HANDLE hModule, Stack DWORD dwReason, Stack LPVOID lpReserved)
BOOL DllMain(HANDLE hModule, DWORD dwReason, LPVOID lpReserved)
{
	word32 edi_12 = edi;
	if (dwReason == 0x01)
		fn10003A13();
	word32 ebp_154 = fn10003ABC(ebx, esi, edi, dwLoc0C, 0x10007720, 0x30);
	Mem29[ebp_154 - 0x20 + 0x00:word32] = 0x01;
	Mem31[ebp_154 - 0x04 + 0x00:word32] = 0x00;
	word32 esp_23 = fp - 0x08;
	word32 esi_157 = 0x00;
	word32 eax_32 = Mem31[ebp_154 + 0x0C:word32];
	if (eax_32 <=u 0x01)
		Mem335[0x100080B0:word32] = eax_32;
	if (Mem31[ebp_154 + 0x0C:word32] == 0x00 && Mem31[0x100080C8:word32] == 0x00)
	{
		Mem334[ebp_154 - 0x20 + 0x00:word32] = 0x00;
		goto l100037EB;
	}
	word32 eax_55 = Mem31[ebp_154 + 0x0C:word32];
	if (eax_55 == 0x01 || eax_55 == 0x02)
	{
		edi_12 = Mem31[0x10008434:word32];
		if (edi_12 != 0x00)
		{
			Mem282[ebp_154 - 0x04 + 0x00:word32] = 0x01;
			if (Mem282[ebp_154 + 0x0C:word32] == 0x01)
				Mem327[0x100080CC:word32] = 0x01;
			Mem287[fp - 0x0C + 0x00:word32] = Mem282[ebp_154 + 0x10:word32];
			Mem290[fp - 0x10 + 0x00:word32] = Mem287[ebp_154 + 0x0C:word32];
			Mem293[fp - 0x14 + 0x00:word32] = Mem290[ebp_154 + 0x08:word32];
			word32 esp_295;
			word32 edi_296;
			word32 ebp_297;
			byte SCZO_298;
			byte Z_299;
			word32 esi_300;
			byte SZO_301;
			byte C_302;
			word32 eax_303;
			byte CZ_304;
			word32 ecx_305;
			word32 ebx_306;
			word32 edx_307;
			selector es_308;
			selector ds_309;
			Mem293[0x1000919C:word32]();
			byte SCZO_313;
			byte Z_314;
			byte SZO_316;
			byte C_317;
			word32 eax_318;
			byte CZ_319;
			word32 ecx_320;
			edi_296();
			Mem325[ebp_154 - 0x20 + 0x00:word32] = eax_318;
			Mem326[ebp_154 - 0x04 + 0x00:word32] = 0x00;
		}
		if (Mem31[ebp_154 - 0x20 + 0x00:word32] == 0x00)
		{
l100037EB:
			Mem51[ebp_154 - 0x04 + 0x00:word32] = ~0x01;
			fn10003802(ebp_154);
			return fn10003B04(Mem51[ebp_154 - 0x20 + 0x00:word32], edx, ebx, ebp_154, esi_157, edi_12, es, ds, 0x30, dwArg00, hModule, dwReason, lpReserved);
		}
		Mem265[ebp_154 - 0x04 + 0x00:word32] = 0x02;
		word32 esp_267 = esp_23 - 0x04;
		Mem268[esp_267 + 0x00:word32] = Mem265[ebp_154 + 0x10:word32];
		Mem271[esp_267 - 0x04 + 0x00:word32] = Mem268[ebp_154 + 0x0C:word32];
		Mem274[esp_267 - 0x08 + 0x00:word32] = Mem271[ebp_154 + 0x08:word32];
		Mem278[ebp_154 - 0x20 + 0x00:word32] = fn10003332(edx, ebp_154, es, ds, dwArg00, hModule, dwReason, out edx);
		esp_23 = esp_267 + 0x04;
		Mem279[ebp_154 - 0x04 + 0x00:word32] = esi_157;
		if (Mem279[ebp_154 - 0x20 + 0x00:word32] == 0x00)
			goto l100037EB;
	}
	Mem71[ebp_154 - 0x04 + 0x00:word32] = 0x03;
	word32 esp_73 = esp_23 - 0x04;
	Mem74[esp_73 + 0x00:word32] = Mem71[ebp_154 + 0x10:word32];
	Mem77[esp_73 - 0x04 + 0x00:word32] = Mem74[ebp_154 + 0x0C:word32];
	Mem80[esp_73 - 0x08 + 0x00:word32] = Mem77[ebp_154 + 0x08:word32];
	Mem84[ebp_154 - 0x20 + 0x00:word32] = fn1000484B(dwArg00, hModule, out edx);
	word32 esp_195 = esp_73 + 0x04;
	Mem85[ebp_154 - 0x04 + 0x00:word32] = esi_157;
	if (Mem85[ebp_154 + 0x0C:word32] == 0x01 && Mem85[(ebp_154 - 0x20) + 0x00:word32] == 0x00)
	{
		Mem173[ebp_154 - 0x04 + 0x00:word32] = 0x04;
		Mem175[esp_73 + 0x00:word32] = esi_157;
		Mem177[esp_73 - 0x04 + 0x00:word32] = esi_157;
		Mem180[esp_73 - 0x08 + 0x00:word32] = Mem177[ebp_154 + 0x08:word32];
		word32 edx_181;
		fn1000484B(dwArg00, hModule, out edx_181);
		Mem184[ebp_154 - 0x04 + 0x00:word32] = esi_157;
		Mem185[ebp_154 - 0x04 + 0x00:word32] = 0x05;
		Mem187[esp_73 + 0x00:word32] = esi_157;
		Mem189[esp_73 - 0x04 + 0x00:word32] = esi_157;
		Mem192[esp_73 - 0x08 + 0x00:word32] = Mem189[ebp_154 + 0x08:word32];
		word32 eax_194 = fn10003332(edx_181, ebp_154, es, ds, dwArg00, hModule, dwReason, out edx);
		esp_195 = esp_73 + 0x04;
		Mem196[ebp_154 - 0x04 + 0x00:word32] = esi_157;
		edi_12 = Mem196[0x10008434:word32];
		if (edi_12 != 0x00)
		{
			Mem201[ebp_154 - 0x04 + 0x00:word32] = 0x06;
			Mem203[esp_73 + 0x00:word32] = esi_157;
			Mem205[esp_73 - 0x04 + 0x00:word32] = esi_157;
			Mem208[esp_73 - 0x08 + 0x00:word32] = Mem205[ebp_154 + 0x08:word32];
			word32 esp_210;
			word32 edi_211;
			word32 ebp_212;
			byte SCZO_213;
			byte Z_214;
			word32 esi_215;
			byte SZO_216;
			byte C_217;
			word32 eax_218;
			byte CZ_219;
			word32 ecx_220;
			word32 ebx_221;
			word32 edx_222;
			selector es_223;
			selector ds_224;
			Mem208[0x1000919C:word32]();
			byte SCZO_228;
			byte Z_229;
			byte SZO_231;
			byte C_232;
			word32 eax_233;
			byte CZ_234;
			word32 ecx_235;
			edi_211();
			Mem240[ebp_154 - 0x04 + 0x00:word32] = esi_157;
		}
	}
	word32 eax_99 = Mem85[ebp_154 + 0x0C:word32];
	if (eax_99 == 0x00 || eax_99 == 0x03)
	{
		Mem105[ebp_154 - 0x04 + 0x00:word32] = 0x07;
		word32 esp_107 = esp_195 - 0x04;
		Mem108[esp_107 + 0x00:word32] = Mem105[ebp_154 + 0x10:word32];
		Mem111[esp_107 - 0x04 + 0x00:word32] = Mem108[ebp_154 + 0x0C:word32];
		Mem114[esp_107 - 0x08 + 0x00:word32] = Mem111[ebp_154 + 0x08:word32];
		word32 eax_116 = fn10003332(edx, ebp_154, es, ds, dwArg00, hModule, dwReason, out edx);
		Mem118[ebp_154 - 0x20 + 0x00:word32] = eax_116;
		Mem119[ebp_154 - 0x04 + 0x00:word32] = esi_157;
		edi_12 = Mem119[0x10008434:word32];
		if (edi_12 != 0x00 && Mem119[0x100080CC:word32] != 0x00)
		{
			Mem126[ebp_154 - 0x04 + 0x00:word32] = 0x08;
			Mem129[esp_107 + 0x00:word32] = Mem126[ebp_154 + 0x10:word32];
			Mem132[esp_107 - 0x04 + 0x00:word32] = Mem129[ebp_154 + 0x0C:word32];
			Mem135[esp_107 - 0x08 + 0x00:word32] = Mem132[ebp_154 + 0x08:word32];
			word32 esp_137;
			word32 edi_138;
			word32 ebp_139;
			byte SCZO_140;
			byte Z_141;
			word32 esi_142;
			byte SZO_143;
			byte C_144;
			word32 eax_145;
			byte CZ_146;
			word32 ecx_147;
			word32 ebx_148;
			word32 edx_149;
			selector es_150;
			selector ds_151;
			Mem135[0x1000919C:word32]();
			word32 esp_152;
			byte SCZO_155;
			byte Z_156;
			byte SZO_158;
			byte C_159;
			word32 eax_160;
			byte CZ_161;
			word32 ecx_162;
			edi_138();
			Mem167[ebp_154 - 0x20 + 0x00:word32] = eax_160;
			Mem168[ebp_154 - 0x04 + 0x00:word32] = esi_157;
		}
	}
	goto l100037EB;
}

// 10003802: void fn10003802(Register word32 ebp)
void fn10003802(word32 ebp)
{
	if (Mem0[ebp + 0x0C:word32] <=u 0x01)
		Mem6[0x100080B0:word32] = ~0x00;
	return;
}

// 10003813: Register word32 fn10003813(Register word32 edx, Register word32 ebx, Register word32 ebp, Register word32 edi, Register selector es, Register selector ds, Stack word32 dwArg04, Stack word32 dwArg08)
word32 fn10003813(word32 edx, word32 ebx, word32 ebp, word32 edi, selector es, selector ds, word32 dwArg04, word32 dwArg08)
{
	word32 edi_3 = edi;
	word32 ebp_118 = fp - 0x04;
	word32 eax_13 = Mem0[0x100080B4:word32] ^ fp - 0x04;
	word32 esp_15 = fp - 0x0C;
	word32 esi_123 = dwArg04;
	word32 eax_120 = 0x00;
	if (dwArg04 <u dwArg08)
	{
		word32 esp_116 = fp - 0x10;
		if (eax_120 == 0x00)
		{
			word32 edi_82 = Mem0[esi_123 + 0x00:word32];
			if (edi_82 != 0x00)
			{
				word32 esp_102;
				word32 edi_103;
				word32 ebp_104;
				word32 ecx_105;
				word32 eax_106;
				byte SZO_107;
				byte C_108;
				word32 esi_109;
				byte SCZO_110;
				byte Z_111;
				word32 edx_112;
				word32 ebx_113;
				selector es_114;
				selector ds_115;
				Mem0[0x1000919C:word32]();
				word32 edi_117;
				word32 ecx_119;
				byte SZO_121;
				byte C_122;
				byte SCZO_124;
				byte Z_125;
				edi_103();
			}
			esi_123 = esi_123 + 0x04;
			if (esi_123 <u dwArg08)
				goto l1000382F;
		}
		edi_3 = Mem0[esp_116 + 0x00:word32];
		esp_15 = esp_116 + 0x04;
	}
	return fn10003870(eax_120, eax_13 ^ fp - 0x04, edx, ebx, ebp_118, Mem0[esp_15 + 0x00:word32], edi_3, es, ds, ebp);
}

// 10003870: Register word32 fn10003870(Register word32 eax, Register word32 ecx, Register word32 edx, Register word32 ebx, Register word32 ebp, Register word32 esi, Register word32 edi, Register selector es, Register selector ds, Stack word32 dwArg00)
word32 fn10003870(word32 eax, word32 ecx, word32 edx, word32 ebx, word32 ebp, word32 esi, word32 edi, selector es, selector ds, word32 dwArg00)
{
	if (ecx != Mem0[0x100080B4:word32])
	{
		Mem33[0x100081D0:word32] = eax;
		Mem34[0x100081CC:word32] = ecx;
		Mem36[0x100081C8:word32] = edx;
		Mem38[0x100081C4:word32] = ebx;
		Mem40[0x100081C0:word32] = esi;
		Mem41[268468668:word32] = edi;
		Mem43[0x100081E8:word16] = ss;
		Mem45[0x100081DC:word16] = cs;
		Mem47[268468664:word16] = ds;
		Mem49[268468660:word16] = es;
		Mem51[0x100081B0:word16] = fs;
		Mem53[0x100081AC:word16] = gs;
		Mem56[0x100081E0:word32] = cond(fp - 808);
		Mem59[0x100081D4:word32] = ebp;
		Mem62[0x100081D8:word32] = dwArg00;
		Mem64[0x100081E4:word32] = fp + 0x04;
		Mem67[0x10008120:word32] = 0x00010001;
		Mem69[268468444:word32] = Mem67[0x100081D8:word32];
		Mem70[0x100080D0:word32] = 0xC0000409;
		Mem71[0x100080D4:word32] = 0x01;
		Mem72[0x100080E0:word32] = 0x03;
		Mem78[0x100080E4:word32] = 0x02;
		Mem85[0x100080E8:word32] = Mem78[0x100080B4:word32];
		Mem92[0x100080EC:word32] = Mem85[0x100080B8:word32];
		return fn10003C01(0x1000102C);
	}
	else
		return eax;
}

// 10003880: Register word32 fn10003880(Register word32 ebx, Register word32 esi, Register word32 edi, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut)
word32 fn10003880(word32 ebx, word32 esi, word32 edi, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut)
{
	word32 ebp_9 = fn10003D4F(ebx, esi, edi, dwLoc08, 0x08);
	Mem13[fp - 0x08 + 0x00:word32] = Mem0[ebp_9 + 0x08:word32];
	Mem15[ebp_9 - 0x04 + 0x00:word32] = Mem13[ebp_9 - 0x04 + 0x00:word32] & 0x00;
	word32 edx_19;
	word32 ebx_20;
	word32 esi_21;
	word32 eax_22 = fn10003EF5(dwArg00, out edx_19, out ebx_20, out esi_21);
	word32 ebx_28;
	word32 ebp_29;
	word32 esi_30;
	fn10003D3B(ebp_9, 0x08, dwArg00, dwArg04, dwArg08, dwArg0C, out ebx_28, out ebp_29, out esi_30);
	return eax_22;
}

// 100038D0: Register word32 fn100038D0(Stack word32 dwArg04, Stack word32 dwArg08, Register out ptr32 edxOut)
word32 fn100038D0(word32 dwArg04, word32 dwArg08, ptr32 & edxOut)
{
	word32 ecx_21 = Mem0[dwArg04 + 0x3C:word32] + dwArg04;
	word32 edx_10;
	*edxOut = 0x00;
	word32 ebx_23 = (word32) Mem0[ecx_21 + 0x06:word16];
	word32 eax_25 = (word32) Mem0[ecx_21 + 0x14:word16] + 0x18 + ecx_21 + 0x0C;
	if (ebx_23 != 0x00)
	{
		do
		{
			word32 esi_58 = Mem0[eax_25 + 0x00:word32];
			if (dwArg08 >=u esi_58 && dwArg08 <u Mem0[eax_25 + 0x08:word32] + esi_58)
				return eax_25;
			edx_10 = edx_10 + 0x01;
			*edxOut = edx_10;
			eax_25 = eax_25 + 0x28;
		} while (edx_10 <u ebx_23);
	}
	eax_25 = 0x00;
	return eax_25;
}

// 10003920: Register word32 fn10003920(Stack word32 dwArg04, Register out ptr32 edxOut)
word32 fn10003920(word32 dwArg04, ptr32 & edxOut)
{
	word32 eax_16 = Mem0[fs:0x00:word32];
	Mem38[fs:0x00:word32] = fp - 0x14;
	word32 edx_43;
	if (fn100039E0(0x10000000, out edx_43) != 0x00)
	{
		word32 edx_96;
		word32 eax_97 = fn100038D0(0x10000000, dwArg04 - 0x10000000, out edx_96);
		if (eax_97 != 0x00)
		{
			word32 eax_104 = ~(Mem38[eax_97 + 0x24:word32] >>u 0x1F);
			Mem110[fs:0x00:word32] = eax_16;
			return eax_104 & 0x01;
		}
	}
	Mem77[fs:0x00:word32] = eax_16;
	return 0x00;
}

// 100039E0: Register word32 fn100039E0(Stack word32 dwArg04, Register out ptr32 edxOut)
word32 fn100039E0(word32 dwArg04, ptr32 & edxOut)
{
	*edxOut = edx;
	if (Mem0[dwArg04 + 0x00:word16] == 23117)
	{
		word32 ecx_38 = Mem0[dwArg04 + 0x3C:word32] + dwArg04;
		word32 eax_40 = 0x00;
		if (Mem0[ecx_38 + 0x00:word32] == 0x4550)
		{
			word32 edx_54;
			*edxOut = 0x010B;
			eax_40 = (word32) (Mem0[ecx_38 + 0x18:word16] == 0x010B);
		}
		return eax_40;
	}
	else
		return 0x00;
}

// 10003A13: void fn10003A13()
void fn10003A13()
{
	word32 eax_18 = Mem0[0x100080B4:word32];
	if (eax_18 != 0xBB40E64E && (eax_18 & 0xFFFF0000) != 0x00)
		Mem95[0x100080B8:word32] = ~eax_18;
	else
	{
		GetSystemTimeAsFileTime(fp - 0x10);
		word32 eax_62 = GetTickCount() ^ (((dwLoc0C & 0x00 ^ dwLoc10 & 0x00) ^ GetCurrentProcessId()) ^ GetCurrentThreadId()) ^ fp - 0x08;
		QueryPerformanceCounter(fp - 0x18);
		word32 ecx_74 = eax_62 ^ (dwLoc14 ^ dwLoc18);
		if (ecx_74 == 0xBB40E64E || (Mem0[0x100080B4:word32] & 0xFFFF0000) == 0x00)
			ecx_74 = ~0x44BF19B0;
		Mem81[0x100080B4:word32] = ecx_74;
		Mem83[0x100080B8:word32] = ~ecx_74;
	}
	return;
}

// 10003ABC: Register word32 fn10003ABC(Register word32 ebx, Register word32 esi, Register word32 edi, Stack word32 dwArg00, Stack word32 dwArg04, Stack word32 dwArg08)
word32 fn10003ABC(word32 ebx, word32 esi, word32 edi, word32 dwArg00, word32 dwArg04, word32 dwArg08)
{
	word32 esp_14 = fp - 0x08 - dwArg08;
	Mem17[esp_14 - 0x04 + 0x00:word32] = ebx;
	Mem20[esp_14 - 0x08 + 0x00:word32] = esi;
	Mem23[esp_14 - 0x0C + 0x00:word32] = edi;
	Mem34[esp_14 - 0x10 + 0x00:word32] = Mem23[0x100080B4:word32] ^ fp + 0x08;
	Mem39[esp_14 - 0x14 + 0x00:word32] = dwArg00;
	Mem44[fs:0x00:word32] = fp - 0x08;
	return fp + 0x08;
}

// 10003B04: Register word32 fn10003B04(Register word32 eax, Register word32 edx, Register word32 ebx, Register word32 ebp, Register word32 esi, Register word32 edi, Register selector es, Register selector ds, Stack word32 dwArg00, Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Stack word32 dwArg10)
word32 fn10003B04(word32 eax, word32 edx, word32 ebx, word32 ebp, word32 esi, word32 edi, selector es, selector ds, word32 dwArg00, word32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10)
{
	word32 eax_16 = fn10003870(eax, Mem0[ebp - 0x1C + 0x00:word32] ^ ebp, edx, ebx, ebp, esi, edi, es, ds, dwLoc04);
	Mem18[fs:0x00:word32] = Mem0[ebp - 0x10 + 0x00:word32];
	Mem38[ebp + 0x00:word32] = dwArg00;
	return eax_16;
}

// 10003C01: Register word32 fn10003C01(Stack word32 dwArg04)
word32 fn10003C01(word32 dwArg04)
{
	SetUnhandledExceptionFilter(0x00);
	UnhandledExceptionFilter(dwArg04);
	return TerminateProcess(GetCurrentProcess(), 0xC0000409);
}

// 10003D3B: Register word32 fn10003D3B(Register word32 ebp, Stack word32 dwArg00, Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Stack word32 dwArg10, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn10003D3B(word32 ebp, word32 dwArg00, word32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	Mem5[fs:0x00:word32] = Mem0[ebp - 0x0C + 0x00:word32];
	word32 ebp_22;
	*ebpOut = Mem5[ebp + 0x00:word32];
	Mem25[ebp + 0x00:word32] = dwArg00;
	word32 esi_17;
	*esiOut = dwArg0C;
	word32 ebx_20;
	*ebxOut = dwArg10;
	return dwArg00;
}

// 10003D4F: Register word32 fn10003D4F(Register word32 ebx, Register word32 esi, Register word32 edi, Stack word32 dwArg00, Stack word32 dwArg04)
word32 fn10003D4F(word32 ebx, word32 esi, word32 edi, word32 dwArg00, word32 dwArg04)
{
	word32 esp_12 = fp - 0x08 - dwArg04;
	Mem15[esp_12 - 0x04 + 0x00:word32] = ebx;
	Mem18[esp_12 - 0x08 + 0x00:word32] = esi;
	Mem21[esp_12 - 0x0C + 0x00:word32] = edi;
	Mem30[esp_12 - 0x10 + 0x00:word32] = Mem21[0x100080B4:word32] ^ fp + 0x04;
	Mem35[esp_12 - 0x14 + 0x00:word32] = dwArg00;
	Mem38[fs:0x00:word32] = fp - 0x08;
	return fp + 0x04;
}

// 10003EF5: Register word32 fn10003EF5(Stack word32 dwArg04, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 esiOut)
word32 fn10003EF5(word32 dwArg04, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & esiOut)
{
fn10003EF5_entry:
	esp = fp
	edi = edi
	esp = fp - 0x04
	dwLoc04 = ebp
	ebp = fp - 0x04
	goto l10003F09
l10003EF5:
l10003EFC:
	v11 = dwArg04
	esp = esp - 0x04
	Mem0[esp + 0x00:word32] = v11
	call callnewh (retsize: 4; depth: 4)
		defs: C,eax,ebp,ebx,ecx,edi,edx,esi,esp,SCZO,SZO,Z
	ecx = Mem0[esp + 0x00:word32]
	esp = esp + 0x04
	SZO = cond(eax & eax)
	Z = SZO (alias)
	C = false
	branch Test(EQ,Z) l10003F19
l10003F09:
	v5 = dwArg04
	esp = esp - 0x04
	Mem0[esp + 0x00:word32] = v5
	eax = malloc(Mem0[esp + 0x00:size_t])
	ecx = Mem0[esp + 0x00:word32]
	esp = esp + 0x04
	SZO = cond(eax & eax)
	Z = SZO (alias)
	C = false
	branch Test(EQ,Z) l10003EFC
l10003F17:
	ebp = Mem0[esp + 0x00:word32]
	esp = esp + 0x04
	return eax
l10003F19:
	eax = fn100042A9(ebp, out edx, out ebx, out ebp, out esi)
	return eax
fn10003EF5_exit:
	use edx (=> edxOut)
	use ebx (=> ebxOut)
	use esi (=> esiOut)
}

// 10003F1E: Register word32 fn10003F1E(Stack word32 dwArg04, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn10003F1E(word32 dwArg04, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	*edxOut = edx;
	*ebxOut = ebx;
	*esiOut = esi;
	word32 eax_42 = 0x00;
	if (dwArg04 != 0x00)
	{
		word32 edx_50;
		word32 ebx_51;
		word32 esi_52;
		eax_42 = fn10003EF5(dwArg04, out edx_50, out ebx_51, out esi_52);
		if (eax_42 == 0x00)
		{
			word32 edx_59;
			word32 ebx_60;
			word32 ebp_61;
			word32 esi_62;
			return fn100042A9(fp - 0x04, out edx_59, out ebx_60, out ebp_61, out esi_62);
		}
	}
	word32 ebp_45;
	*ebpOut = Mem0[fp - 0x04 + 0x00:word32];
	return eax_42;
}

// 10003F93: void fn10003F93(Register word32 ecx)
void fn10003F93(word32 ecx)
{
	exception(ecx, fp - 0x08, 0x01);
	Mem22[ecx + 0x00:word32] = 0x10001034;
	return;
}

// 10003FE3: void fn10003FE3(Register word32 ecx, Stack word32 dwArg04)
void fn10003FE3(word32 ecx, word32 dwArg04)
{
	exception(ecx, fp - 0x08);
	Mem23[ecx + 0x00:word32] = 0x1000103C;
	return;
}

// 100040D1: Register word32 fn100040D1(Register word32 ecx, Register word32 ebx, Register word32 esi, Register word32 edi, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 esiOut)
word32 fn100040D1(word32 ecx, word32 ebx, word32 esi, word32 edi, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & esiOut)
{
	word32 ebp_9 = fn10003D4F(ebx, esi, edi, dwLoc08, 0x10);
	Mem12[ebp_9 - 0x18 + 0x00:word32] = ecx;
	word32 edi_13 = Mem12[ebp_9 + 0x08:word32];
	word32 edi_109 = edi_13 | 0x0F;
	if ((edi_13 | 0x0F) >u ~0x01)
		edi_109 = Mem12[ebp_9 + 0x08:word32];
	else
	{
		Mem111[ebp_9 - 0x14 + 0x00:word32] = 0x03;
		word32 ebx_114 = Mem111[ecx + 0x14:word32];
		if (ebx_114 >>u 0x01 >u (uint32) ((uint64) ((uint32) (edi_13 | 0x0F)) /u Mem111[(ebp_9 - 0x14) + 0x00:word32]))
		{
			Mem124[fp - 0x08 + 0x00:word32] = ~0x01;
			if (ebx_114 <=u Mem124[(fp - 0x08) + 0x00:word32] - (ebx_114 >>u 0x01))
				edi_109 = (ebx_114 >>u 0x01) + ebx_114;
			else
			{
				Mem132[fp - 0x08 + 0x00:word32] = ~0x01;
				edi_109 = Mem132[fp - 0x08 + 0x00:word32];
			}
		}
	}
	Mem27[fp - 0x08 + 0x00:word32] = 0x00;
	Mem29[fp - 0x0C + 0x00:word32] = edi_109 + 0x01;
	Mem30[ebp_9 - 0x04 + 0x00:word32] = 0x00;
	word32 edx_32;
	word32 ebx_33;
	word32 ebp_34;
	word32 esi_35;
	word32 eax_36 = fn10003F1E(dwArg00, out edx_32, out ebx_33, out ebp_34, out esi_35);
	Mem44[ebp_34 - 0x14 + 0x00:word32] = eax_36;
	word32 eax_45 = Mem44[ebp_34 + 0x0C:word32];
	if (eax_45 != 0x00)
	{
		word32 edx_105;
		if (Mem44[esi_35 + 0x14:word32] >=u 0x10)
			*edxOut = Mem44[esi_35 + 0x00:word32];
		else
			*edxOut = esi_35;
		if (eax_45 != 0x00)
		{
			Mem96[fp - 0x04 + 0x00:word32] = eax_45;
			Mem98[fp - 0x08 + 0x00:word32] = edx_105;
			Mem100[fp - 0x0C + 0x00:word32] = eax_36;
			memcpy(Mem100[fp - 0x0C + 0x00:(ptr void)], Mem100[fp - 0x08 + 0x00:(ptr void)], Mem100[fp - 0x04 + 0x00:size_t]);
		}
	}
	Mem56[fp - 0x04 + 0x00:word32] = ebx_33;
	Mem58[fp - 0x08 + 0x00:word32] = 0x01;
	fn10004263(esi_35, bArg00, dwArg04);
	if (esi_35 != 0x00)
		Mem87[esi_35 + 0x00:word32] = Mem58[ebp_34 - 0x14 + 0x00:word32];
	word32 eax_67 = Mem58[ebp_34 + 0x0C:word32];
	Mem69[esi_35 + 0x14:word32] = edi_109;
	Mem70[esi_35 + 0x10:word32] = eax_67;
	if (edi_109 >=u 0x10)
		esi_35 = Mem70[esi_35 + 0x00:word32];
	Mem74[esi_35 + eax_67:byte] = 0x00;
	word32 ebx_77;
	word32 ebp_78;
	word32 esi_79;
	return fn10003D3B(ebp_34, 0x10, dwArg00, dwArg04, dwArg08, dwArg0C, out ebx_77, out ebp_78, out esi_79);
}

// 100041C8: Register byte fn100041C8(Register word32 ecx, Register word32 ebx, Register word32 ebp, Register word32 edi, Stack word32 dwArg04, Stack byte bArg08, Register out ptr32 ecxOut, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
byte fn100041C8(word32 ecx, word32 ebx, word32 ebp, word32 edi, word32 dwArg04, byte bArg08, ptr32 & ecxOut, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	*ecxOut = ecx;
	*ebxOut = ebx;
	*edxOut = edx;
	word32 esi_12 = dwArg04;
	if (dwArg04 >u ~0x01)
	{
		word32 ebx_124;
		word32 ebp_125;
		word32 esi_126;
		word32 ecx_127 = fn100042C8(out ebx_124, out ebp_125, out esi_126);
		*ecxOut = ecx_127;
		int3();
		word32 edx_129;
		return fn10004226(ecx_127, dwArg00, out edx_129);
	}
	byte Z_47;
	if (Mem0[ecx + 0x14:word32] <u dwArg04)
	{
		word32 edx_80;
		word32 ebx_81;
		word32 ecx_83;
		*ecxOut = fn100040D1(ecx, ebx, dwArg04, edi, out edx_80, out ebx_81, out esi_12);
	}
	else if (bArg08 != 0x00 && dwArg04 <u 0x10)
	{
		word32 eax_109 = Mem0[ecx + 0x10:word32];
		if (dwArg04 <u eax_109)
			eax_109 = dwArg04;
		word32 ecx_120;
		*ecxOut = fn10004263(ecx, 0x01, eax_109);
	}
	else
	{
		Z_47 = cond(dwArg04);
		if (dwArg04 != 0x00)
		{
l10004218:
			word32 esi_55;
			*esiOut = Mem0[fp - 0x08 + 0x00:word32];
			word32 ebp_57;
			*ebpOut = Mem0[fp - 0x04 + 0x00:word32];
			return Z_47;
		}
		Mem100[ecx + 0x10:word32] = Mem0[ecx + 0x10:word32] & dwArg04;
		if (Mem100[ecx + 0x14:word32] >=u 0x10)
			*ecxOut = Mem100[ecx + 0x00:word32];
		Mem105[ecx + 0x00:byte] = 0x00;
	}
	Z_47 = cond(esi_12);
	goto l10004218;
}

// 10004226: Register byte fn10004226(Register word32 ecx, Stack word32 dwArg04, Register out ptr32 edxOut)
byte fn10004226(word32 ecx, word32 dwArg04, ptr32 & edxOut)
{
	byte al_24;
	word32 edx_9;
	*edxOut = dwArg04;
	if (dwArg04 != 0x00)
	{
		word32 eax_44;
		if (Mem0[ecx + 0x14:word32] >=u 0x10)
			eax_44 = Mem0[ecx + 0x00:word32];
		else
			eax_44 = ecx;
		if (dwArg04 >=u eax_44)
		{
			word32 esi_51;
			if (Mem0[ecx + 0x14:word32] >=u 0x10)
				esi_51 = Mem0[ecx + 0x00:word32];
			else
				esi_51 = ecx;
			if (Mem0[ecx + 0x10:word32] + esi_51 >u dwArg04)
			{
				al_24 = 0x01;
				return al_24;
			}
		}
	}
	al_24 = 0x00;
	return al_24;
}

// 10004263: Register word32 fn10004263(Register word32 ecx, Stack byte bArg04, Stack word32 dwArg08)
word32 fn10004263(word32 ecx, byte bArg04, word32 dwArg08)
{
	word32 ecx_37;
	ecx_37 = ecx;
	if (bArg04 != 0x00)
	{
		ecx_37 = ecx;
		if (Mem0[ecx + 0x14:word32] >=u 0x10)
		{
			word32 ebx_53 = Mem0[ecx + 0x00:word32];
			if (dwArg08 != 0x00)
				memcpy(ecx, ebx_53, dwArg08);
			operator delete(ebx_53);
			ecx_37 = ebx_53;
		}
	}
	Mem39[ecx + 0x10:word32] = dwArg08;
	Mem40[ecx + 0x14:word32] = 0x0F;
	Mem41[dwArg08 + ecx:byte] = 0x00;
	return ecx_37;
}

// 100042A9: Register word32 fn100042A9(Register word32 ebp, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn100042A9(word32 ebp, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	Mem6[v3 - 0x04 + 0x00:word32] = ebp;
	fn10003F93(v3 - 0x10);
	Mem12[v3 - 0x14 + 0x00:word32] = 0x100078C0;
	Mem15[v3 - 0x18 + 0x00:word32] = v3 - 0x10;
	word32 esp_16;
	word32 edi_17;
	word32 ebp_18;
	word32 eax_19;
	word32 ecx_20;
	byte SZO_21;
	byte C_22;
	byte Z_23;
	byte SCZO_24;
	word32 edx_25;
	word32 ebx_26;
	word32 esi_27;
	CxxThrowException();
	int3();
	Mem29[v3 - 0x1C + 0x00:word32] = 0x10001AE8;
	word32 ecx_31;
	word32 edx_32;
	word32 ebx_33;
	word32 ebp_34;
	word32 esi_35;
	fn100042D3(dwArg00, out ecx_31, out edx_32, out ebx_33, out ebp_34, out esi_35);
	word32 ecx_37;
	word32 edx_38;
	word32 ebx_39;
	word32 ebp_40;
	word32 esi_41;
	return fn100042D2(out ecx_37, out edx_38, out ebx_39, out ebp_40, out esi_41);
}

// 100042C8: Register word32 fn100042C8(Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn100042C8(ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	word32 ecx_4;
	word32 edx_5;
	word32 ebx_6;
	word32 ebp_7;
	word32 esi_8;
	fn100042D3(0x10001AE8, out ecx_4, out edx_5, out ebx_6, out ebp_7, out esi_8);
	word32 ecx_10;
	word32 edx_11;
	word32 ebx_12;
	word32 ebp_13;
	word32 esi_14;
	fn100042D2(out ecx_10, out edx_11, out ebx_12, out ebp_13, out esi_14);
	return ecx_10;
}

// 100042D2: Register word32 fn100042D2(Register out ptr32 ecxOut, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn100042D2(ptr32 & ecxOut, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
fn100042D2_entry:
	def fp
	def dwArg04
	def ecxOut
	def edxOut
	def ebxOut
	def ebpOut
	def esiOut
	esp_1 = fp
	int3()
	eax_8 = fn100042D3(dwArg04, out ecx_3, out edx_4, out ebx_5, out ebp_6, out esi_7)
	return eax_8
l100042D2:
l100042D2:
	int3()
	eax = fn100042D3(dwArg04, out ecx, out edx, out ebx, out ebp, out esi)
	return eax
l100042D2_thunk_fn100042D3:
l100042D2_thunk_fn100042D3:
fn100042D2_exit:
	ecx_9 = PHI(ecx_3, ecx)
	edx_10 = PHI(edx_4, edx)
	ebx_11 = PHI(ebx_5, ebx)
	ebp_12 = PHI(ebp_6, ebp)
	esi_13 = PHI(esi_7, esi)
	eax_14 = PHI(eax_8, eax)
	use ecx_9 (=> ecxOut)
	use edx_10 (=> edxOut)
	use ebx_11 (=> ebxOut)
	use ebp_12 (=> ebpOut)
	use esi_13 (=> esiOut)
}

// 100042D3: Register word32 fn100042D3(Stack word32 dwArg04, Register out ptr32 ecxOut, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn100042D3(word32 dwArg04, ptr32 & ecxOut, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	fn10003FE3(fp - 0x10, dwArg04);
	word32 esp_21;
	word32 edi_22;
	word32 ebp_23;
	byte SCZO_24;
	word32 ecx_25;
	word32 eax_26;
	word32 edx_27;
	word32 ebx_28;
	word32 esi_29;
	CxxThrowException();
	int3();
	fn10003FE3(fp - 0x28, 0x10007930);
	word32 esp_46;
	word32 edi_47;
	word32 ebp_48;
	byte SCZO_49;
	word32 ecx_50;
	word32 eax_51;
	word32 edx_52;
	word32 ebx_53;
	word32 esi_54;
	CxxThrowException();
	int3();
	word32 ebx_57;
	word32 ebp_58;
	word32 esi_59;
	word32 edi_60;
	word32 ecx_61 = fn100042F5(0x10001AD0, out ebx_57, out ebp_58, out esi_59, out edi_60);
	word32 ecx_62;
	word32 edx_63;
	word32 ebx_64;
	word32 ebp_65;
	word32 esi_66;
	word32 edi_67;
	return fn10004321(ecx_61, out ecx_62, out edx_63, out ebx_64, out ebp_65, out esi_66, out edi_67);
}

// 100042F5: Register word32 fn100042F5(Stack word32 dwArg04, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn100042F5(word32 dwArg04, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	fn10003FE3(fp - 0x10, dwArg04);
	word32 esp_21;
	word32 edi_22;
	word32 ebp_23;
	byte SCZO_24;
	word32 ecx_25;
	word32 eax_26;
	word32 ebx_27;
	word32 esi_28;
	byte C_29;
	byte al_30;
	byte SZO_31;
	byte Z_32;
	word32 edx_33;
	CxxThrowException();
	int3();
	word32 ebx_36;
	word32 ebp_37;
	word32 esi_38;
	word32 edi_39;
	word32 ecx_40 = fn100042F5(0x10001AD0, out ebx_36, out ebp_37, out esi_38, out edi_39);
	int3();
	Mem43[fp - 0x20 + 0x00:word32] = ebp_37;
	word32 eax_45 = Mem43[fp - 0x14 + 0x00:word32];
	Mem48[fp - 0x24 + 0x00:word32] = ebx_36;
	word32 ebx_49 = Mem48[fp - 0x18 + 0x00:word32];
	Mem51[fp - 0x28 + 0x00:word32] = esi_38;
	Mem53[fp - 44 + 0x00:word32] = edi_39;
	word32 edi_55 = Mem53[ebx_49 + 0x10:word32];
	if (edi_55 <u eax_45)
	{
		word32 edx_76;
		word32 ebx_77;
		word32 ebp_78;
		word32 esi_79;
		word32 edi_80;
		fn100043AE(out edx_76, out ebx_77, out ebp_78, out esi_79, out edi_80);
		return ecx_40;
	}
	else
	{
		word32 ecx_69;
		word32 edx_70;
		word32 ebx_71;
		word32 ebp_72;
		word32 esi_73;
		word32 edi_74;
		fn10004339(eax_45, ecx_40, ebx_49, fp - 0x20, ecx_40, edi_55, out ecx_69, out edx_70, out ebx_71, out ebp_72, out esi_73, out edi_74);
		return ecx_69;
	}
}

// 10004317: Register word32 fn10004317(Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn10004317(ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	word32 ebx_4;
	word32 ebp_5;
	word32 esi_6;
	word32 edi_7;
	word32 ecx_8 = fn100042F5(0x10001AD0, out ebx_4, out ebp_5, out esi_6, out edi_7);
	word32 ecx_9;
	word32 edx_10;
	word32 ebx_11;
	word32 ebp_12;
	word32 esi_13;
	word32 edi_14;
	fn10004321(ecx_8, out ecx_9, out edx_10, out ebx_11, out ebp_12, out esi_13, out edi_14);
	return ecx_9;
}

// 10004321: Register word32 fn10004321(Register word32 ecx, Register out ptr32 ecxOut, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn10004321(word32 ecx, ptr32 & ecxOut, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
fn10004321_entry:
	def fp
	def ecx
	def dwArg04
	def dwArg08
	def ecxOut
	def edxOut
	def ebxOut
	def ebpOut
	def esiOut
	def ediOut
	esp_1 = fp
	int3()
	eax_11 = fn10004322(ecx, dwArg04, dwArg08, out ecx_5, out edx_6, out ebx_7, out ebp_8, out esi_9, out edi_10)
	return eax_11
l10004321:
l10004321:
	int3()
	edi = edi
	esp = esp - 0x04
	Mem0[esp + 0x00:word32] = ebp
	ebp = esp
	eax = Mem0[ebp + 0x0C:word32]
	esp = esp - 0x04
	Mem0[esp + 0x00:word32] = ebx
	ebx = Mem0[ebp + 0x08:word32]
	esp = esp - 0x04
	Mem0[esp + 0x00:word32] = esi
	esp = esp - 0x04
	Mem0[esp + 0x00:word32] = edi
	esi = ecx
	edi = Mem0[ebx + 0x10:word32]
	SCZO = cond(edi - eax)
	C = SCZO (alias)
	branch Test(ULT,C) l10004337_thunk_fn100043AE
l10004321_thunk_fn10004322:
l10004337_thunk_fn10004339:
	eax = fn10004339(eax, ecx, ebx, ebp, esi, edi, out ecx, out edx, out ebx, out ebp, out esi, out edi)
	return eax
l10004337_thunk_fn10004339:
	eax = fn10004339(eax, ecx, ebx, ebp, esi, edi, out ecx, out edx, out ebx, out ebp, out esi, out edi)
	return eax
l10004337_thunk_fn100043AE:
	eax = fn100043AE(out edx, out ebx, out ebp, out esi, out edi)
	return eax
fn10004321_exit:
	ecx_12 = PHI(ecx_5, ecx, ecx, ecx)
	edx_13 = PHI(edx_6, edx, edx, edx)
	ebx_14 = PHI(ebx_7, ebx, ebx, ebx)
	ebp_15 = PHI(ebp_8, ebp, ebp, ebp)
	esi_16 = PHI(esi_9, esi, esi, esi)
	edi_17 = PHI(edi_10, edi, edi, edi)
	eax_18 = PHI(eax_11, eax, eax, eax)
	use ecx_12 (=> ecxOut)
	use edx_13 (=> edxOut)
	use ebx_14 (=> ebxOut)
	use ebp_15 (=> ebpOut)
	use esi_16 (=> esiOut)
	use edi_17 (=> ediOut)
}

// 10004322: Register word32 fn10004322(Register word32 ecx, Stack word32 dwArg04, Stack word32 dwArg08, Register out ptr32 ecxOut, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn10004322(word32 ecx, word32 dwArg04, word32 dwArg08, ptr32 & ecxOut, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	*ecxOut = ecx;
	word32 edi_23 = Mem0[dwArg04 + 0x10:word32];
}

// 10004339: Register word32 fn10004339(Register word32 eax, Register word32 ecx, Register word32 ebx, Register word32 ebp, Register word32 esi, Register word32 edi, Register out ptr32 ecxOut, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn10004339(word32 eax, word32 ecx, word32 ebx, word32 ebp, word32 esi, word32 edi, ptr32 & ecxOut, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	word32 edi_109 = edi - eax;
	if (Mem0[ebp + 0x10:word32] <u edi_109)
		edi_109 = Mem0[ebp + 0x10:word32];
	word32 esp_21;
	word32 esi_20;
	if (esi == ebx)
	{
		Mem42[v3 - 0x04 + 0x00:word32] = eax + edi_109;
		word32 ebp_45;
		word32 esi_46;
		word32 ebx_47 = fn100044EA(ecx, dwArg00, out ebp_45, out esi_46);
		Mem52[v3 - 0x04 + 0x00:word32] = Mem42[ebp_45 + 0x0C:word32];
		Mem54[v3 - 0x08 + 0x00:word32] = 0x00;
		esp_21 = v3 - 0x08;
		word32 edx_55;
		word32 ecx_57;
		*ecxOut = fn10004516(esi_46, ebx_47, dwArg00, out edx_55, out esi_20);
	}
	else
	{
		Mem60[v3 - 0x04 + 0x00:word32] = 0x00;
		Mem62[v3 - 0x08 + 0x00:word32] = edi_109;
		esp_21 = v3;
		word32 ecx_64;
		word32 edx_65;
		word32 ebp_67;
		word32 ebx_108;
		if (fn100041C8(ecx, ebx, ebp, edi_109, dwArg00, bArg04, out ecx_64, out edx_65, out ebx_108, out ebp_67, out esi_20) != 0x00)
		{
			if (Mem62[ebx_108 + 0x14:word32] >=u 0x10)
				ebx_108 = Mem62[ebx_108 + 0x00:word32];
			word32 ecx_106;
			if (Mem62[esi_20 + 0x14:word32] >=u 0x10)
				*ecxOut = Mem62[esi_20 + 0x00:word32];
			else
				*ecxOut = esi_20;
			if (edi_109 != 0x00)
			{
				word32 eax_95 = Mem62[ebp_67 + 0x0C:word32];
				Mem97[v3 - 0x04 + 0x00:word32] = edi_109;
				Mem100[v3 - 0x08 + 0x00:word32] = eax_95 + ebx_108;
				Mem102[v3 - 0x0C + 0x00:word32] = ecx_106;
				memcpy(Mem102[v3 - 0x0C + 0x00:(ptr void)], Mem102[v3 - 0x08 + 0x00:(ptr void)], Mem102[v3 - 0x04 + 0x00:size_t]);
			}
			word32 eax_88;
			Mem87[esi_20 + 0x10:word32] = edi_109;
			esp_21 = v3;
			if (Mem62[esi_20 + 0x14:word32] >=u 0x10)
				eax_88 = Mem87[esi_20 + 0x00:word32];
			else
				eax_88 = esi_20;
			Mem90[eax_88 + edi_109:byte] = 0x00;
		}
	}
	word32 esp_24 = esp_21 + 0x04;
	word32 edi_23;
	*ediOut = Mem0[esp_21 + 0x00:word32];
	word32 esi_27;
	*esiOut = Mem0[esp_24 + 0x00:word32];
	word32 ebx_29;
	*ebxOut = Mem0[esp_24 + 0x04:word32];
	word32 ebp_31;
	*ebpOut = Mem0[esp_24 + 0x08:word32];
	return esi_20;
}

// 100043AE: Register word32 fn100043AE(Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn100043AE(ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	esp = v3;
	ecx = fn10004317(out edx, out ebx, out ebp, out esi, out edi);
	int3();
	edi = edi;
	esp = esp - 0x04;
	Mem0[esp + 0x00:word32] = ebp;
	ebp = esp;
	esp = esp - 0x04;
	Mem0[esp + 0x00:word32] = ebx;
	ebx = Mem0[ebp + 0x08:word32];
	esp = esp - 0x04;
	Mem0[esp + 0x00:word32] = esi;
	esp = esp - 0x04;
	Mem0[esp + 0x00:word32] = ebx;
	esi = ecx;
	al = fn10004226(ecx, dwArg00, out edx);
	esp = esp + 0x04;
	SZO = cond(al & al);
	C = false;
	if (Test(NE,Z))
	{
		SCZO = cond(Mem0[esi + 0x14:word32] - 0x10);
		if (Test(UGE,C))
			eax = Mem0[esi + 0x00:word32];
		else
			eax = esi;
		v14 = Mem0[ebp + 0x0C:word32];
		esp = esp - 0x04;
		Mem0[esp + 0x00:word32] = v14;
		ebx = ebx - eax;
		SCZO = cond(ebx);
		ecx = esi;
		esp = esp - 0x04;
		Mem0[esp + 0x00:word32] = ebx;
		esp = esp - 0x04;
		Mem0[esp + 0x00:word32] = esi;
		eax = fn10004322(ecx, dwArg00, dwArg04, out ecx, out edx, out ebx, out ebp, out esi, out edi);
	}
	else
	{
		esp = esp - 0x04;
		Mem0[esp + 0x00:word32] = edi;
		edi = Mem0[ebp + 0x0C:word32];
		ecx = esi;
		esp = esp - 0x04;
		Mem0[esp + 0x00:word32] = 0x00;
		esp = esp - 0x04;
		Mem0[esp + 0x00:word32] = edi;
		al = fn100041C8(ecx, ebx, ebp, edi, dwArg00, bArg04, out ecx, out edx, out ebx, out ebp, out esi);
		esp = esp + 0x08;
		SZO = cond(al & al);
		C = false;
		if (Test(NE,Z))
		{
			SCZO = cond(Mem0[esi + 0x14:word32] - 0x10);
			if (Test(UGE,C))
				eax = Mem0[esi + 0x00:word32];
			else
				eax = esi;
			SZO = cond(edi & edi);
			C = false;
			if (Test(NE,Z))
			{
				esp = esp - 0x04;
				Mem0[esp + 0x00:word32] = edi;
				esp = esp - 0x04;
				Mem0[esp + 0x00:word32] = ebx;
				esp = esp - 0x04;
				Mem0[esp + 0x00:word32] = eax;
				eax = memcpy(Mem0[esp + 0x00:(ptr void)], Mem0[esp + 0x04:(ptr void)], Mem0[esp + 0x08:size_t]);
				esp = esp + 0x0C;
				SCZO = cond(esp);
			}
			SCZO = cond(Mem0[esi + 0x14:word32] - 0x10);
			Mem0[esi + 0x10:word32] = edi;
			if (Test(UGE,C))
				eax = Mem0[esi + 0x00:word32];
			else
				eax = esi;
			Mem0[eax + edi:byte] = 0x00;
		}
		eax = esi;
		edi = Mem0[esp + 0x00:word32];
		esp = esp + 0x04;
	}
	esi = Mem0[esp + 0x00:word32];
	esp = esp + 0x04;
	ebx = Mem0[esp + 0x00:word32];
	esp = esp + 0x04;
	ebp = Mem0[esp + 0x00:word32];
	esp = esp + 0x04;
	return eax;
}

// 100044EA: Register word32 fn100044EA(Register word32 ecx, Stack word32 dwArg04, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn100044EA(word32 ecx, word32 dwArg04, ptr32 & ebpOut, ptr32 & esiOut)
{
	*esiOut = esi;
	if (Mem0[ecx + 0x10:word32] <u dwArg04)
	{
		word32 edx_40;
		word32 ebx_41;
		word32 ebp_42;
		word32 esi_43;
		word32 edi_44;
		word32 ecx_45 = fn10004317(out edx_40, out ebx_41, out ebp_42, out esi_43, out edi_44);
		int3();
		Mem48[fp - 0x08 + 0x00:word32] = ebp_42;
		Mem51[fp - 0x0C + 0x00:word32] = esi_43;
		word32 ecx_53 = Mem51[fp + 0x00:word32];
		Mem56[fp - 0x10 + 0x00:word32] = edi_44;
		word32 edi_57 = Mem56[ecx_45 + 0x10:word32];
		if (edi_57 <u ecx_53)
		{
			word32 edx_64;
			word32 ebx_65;
			word32 ebp_66;
			word32 esi_67;
			fn10004590(out edx_64, out ebx_65, out ebp_66, out esi_67);
			return ebx_65;
		}
		else
		{
			word32 ebx_60;
			word32 ebp_61;
			word32 esi_62;
			fn10004529(ecx_53, ebx_41, fp - 0x08, ecx_45, edi_57, out ebx_60, out ebp_61, out esi_62);
			return ebx_60;
		}
	}
	else
	{
		word32 edx_30;
		Mem29[ecx + 0x10:word32] = dwArg04;
		if (Mem0[ecx + 0x14:word32] >=u 0x10)
			edx_30 = Mem29[ecx + 0x00:word32];
		else
			edx_30 = ecx;
		Mem31[edx_30 + dwArg04:byte] = 0x00;
		word32 ebp_33;
		*ebpOut = ebp;
		return ebx;
	}
}

// 10004516: Register word32 fn10004516(Register word32 ecx, Register word32 ebx, Stack word32 dwArg04, Register out ptr32 edxOut, Register out ptr32 esiOut)
word32 fn10004516(word32 ecx, word32 ebx, word32 dwArg04, ptr32 & edxOut, ptr32 & esiOut)
{
	word32 edi_18 = Mem0[ecx + 0x10:word32];
}

// 10004529: Register word32 fn10004529(Register word32 ecx, Register word32 ebx, Register word32 ebp, Register word32 esi, Register word32 edi, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn10004529(word32 ecx, word32 ebx, word32 ebp, word32 esi, word32 edi, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	*ebxOut = ebx;
	word32 edx_4 = Mem0[ebp + 0x0C:word32];
	if (edi - ecx <=u edx_4)
	{
		word32 eax_31;
		Mem30[esi + 0x10:word32] = ecx;
		if (Mem0[esi + 0x14:word32] >=u 0x10)
			eax_31 = Mem30[esi + 0x00:word32];
		else
			eax_31 = esi;
		Mem32[eax_31 + ecx:byte] = 0x00;
	}
	else if (edx_4 != 0x00)
	{
		word32 eax_43;
		if (Mem0[esi + 0x14:word32] >=u 0x10)
			eax_43 = Mem0[esi + 0x00:word32];
		else
			eax_43 = esi;
		Mem46[v3 - 0x04 + 0x00:word32] = ebx;
		word32 edi_44 = edi - edx_4;
		word32 ebx_47 = eax_43 + ecx;
		word32 eax_49 = edi_44 - ecx;
		if (eax_49 != 0x00)
		{
			Mem64[v3 - 0x08 + 0x00:word32] = eax_49;
			Mem67[v3 - 0x0C + 0x00:word32] = ebx_47 + edx_4;
			Mem69[v3 - 0x10 + 0x00:word32] = ebx_47;
			memmove(Mem69[v3 - 0x10 + 0x00:(ptr void)], Mem69[v3 - 0x0C + 0x00:(ptr void)], Mem69[v3 - 0x08 + 0x00:size_t]);
		}
		word32 eax_59;
		Mem56[esi + 0x10:word32] = edi_44;
		word32 ebx_57;
		*ebxOut = Mem56[v3 - 0x04 + 0x00:word32];
		if (Mem46[esi + 0x14:word32] >=u 0x10)
			eax_59 = Mem56[esi + 0x00:word32];
		else
			eax_59 = esi;
		Mem60[eax_59 + edi_44:byte] = 0x00;
	}
	word32 esi_21;
	*esiOut = Mem0[v3 + 0x04:word32];
	word32 ebp_23;
	*ebpOut = Mem0[v3 + 0x08:word32];
	return edx_4;
}

// 10004590: Register word32 fn10004590(Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut)
word32 fn10004590(ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	word32 edx_4;
	word32 ebx_5;
	word32 ebp_6;
	word32 esi_7;
	word32 edi_8;
	word32 ecx_38 = fn10004317(out edx_4, out ebx_5, out ebp_6, out esi_7, out edi_8);
	int3();
	Mem13[v3 - 0x04 + 0x00:word32] = ebp_6;
	word32 eax_15 = Mem13[v3 + 0x04:word32];
	if (Mem13[eax_15 + 0x00:byte] != 0x00)
	{
		word32 edx_37;
		*edxOut = eax_15 + 0x01;
		do
		{
			byte cl_40 = Mem13[eax_15 + 0x00:byte];
			ecx_38 = DPB(ecx_38, cl_40, 0);
			eax_15 = eax_15 + 0x01;
		} while (cl_40 != 0x00);
		word32 ebp_48;
		*ebpOut = Mem13[v3 - 0x04 + 0x00:word32];
		return ecx_38;
	}
	else
	{
		word32 ebp_35;
		*ebpOut = Mem13[v3 - 0x04 + 0x00:word32];
		return ecx_38;
	}
}

// 1000484B: Register word32 fn1000484B(Stack word32 dwArg04, Stack word32 dwArg08, Register out ptr32 edxOut)
word32 fn1000484B(word32 dwArg04, word32 dwArg08, ptr32 & edxOut)
{
	*edxOut = edx;
	if (dwArg08 != 0x00)
	{
		if (dwArg08 == 0x01)
		{
			fn100031B0();
			Mem38[0x10008440:word32] = 268444812;
			Mem39[0x1000800C:word32] = 0x10008448;
			fn10003100();
			DisableThreadLibraryCalls(dwArg04);
		}
	}
	else
	{
		word32 edx_44;
		*edxOut = fn10003160();
	}
	Mem25[0x10008438:word32] = dwArg04;
	return 0x01;
}

// 10004EAB: Register word32 fn10004EAB(Register word32 ecx, Register word32 edx, Register out ptr32 edxOut)
word32 fn10004EAB(word32 ecx, word32 edx, ptr32 & edxOut)
{
	*edxOut = edx;
	word32 esi_14 = 0x0C;
l10004EB3:
	word32 ecx_22;
	word32 eax_16 = Mem0[ecx + 0x00:word32];
	byte al_17 = (byte) eax_16;
	if (eax_16 != Mem0[edx + 0x00:word32])
	{
		byte C_48 = cond(al_17 - Mem0[edx + 0x00:byte]);
		if (al_17 == Mem0[edx + 0x00:byte])
		{
			byte al_57 = Mem0[ecx + 0x01:byte];
			C_48 = cond(al_57 - Mem0[edx + 0x01:byte]);
			if (al_57 == Mem0[edx + 0x01:byte])
			{
				byte al_62 = Mem0[ecx + 0x02:byte];
				C_48 = cond(al_62 - Mem0[edx + 0x02:byte]);
				if (al_62 == Mem0[edx + 0x02:byte])
				{
					byte al_67 = Mem0[ecx + 0x03:byte];
					C_48 = cond(al_67 - Mem0[edx + 0x03:byte]);
					if (al_67 == Mem0[edx + 0x03:byte])
						break;
				}
			}
		}
		ecx_22 = 0x00 - C_48 | 0x01;
		return (word32) (ecx_22 == 0x00);
	}
	else
	{
		ecx = ecx + 0x04;
		*edxOut = edx + 0x04;
		esi_14 = esi_14 - 0x04;
		if (esi_14 >=u 0x00)
			goto l10004EB3;
		ecx_22 = 0x00;
		return (word32) (ecx_22 == 0x00);
	}
}

