// credprovhost.c
// Generated by decompiling credprovhost.dll
// using Reko decompiler version 0.7.1.0.

#include "credprovhost.h"

Eq_2267 g_tC0000001;
Eq_16879 g_tFFFFFFFC;
word16 g_wFFFFFFFE;
Eq_47530 g_a0000[];
Eq_81447 g_a0001[];
word32 g_dw0002;
Eq_77425 g_t0004;
word32 g_dw0008;
ui32 g_dw000C;
ui32 g_dw001C;
Eq_26823 g_t0034;
Eq_49323 g_t0044;
Eq_47497 g_t0054;
word32 g_dw006B;
word32 g_dw006C;
word32 g_dw006D;
word32 g_dw006E;
word32 g_dw006F;
word32 g_dw0071;
word32 g_dw0072;
word32 g_dw0073;
word32 g_dw0074;
word32 g_dw0075;
word32 g_dw0076;
word32 g_dw0077;
Eq_42490 g_t007C;
Eq_2 g_t0080;
Eq_80425 g_t10000000 = 
	{
		0x5A4D,
		0x00000100,
	};
Eq_80623 g_t10001000 = 
	{
		&g_dw100310F0,
		&g_dw10031140,
	};
word32 g_dw10001628 = 0x1001E900;
word32 g_dw100017FC = 0x100229D0;
Eq_2 g_t1000180C = 
	{
		true
	};
word32 g_dw1000182C = 0x10022AA0;
word32 g_dw1000190C = 0x100229D0;
Eq_2 g_t1000191C = 
	{
		true
	};
word32 g_dw1000193C = 0x10022AA0;
word32 g_dw10002064 = 0x00000000;
word32 g_dw10002070 = 0x00000000;
word32 g_dw1000309C = 0x905A0FE6;
word32 g_dw100030A0 = 0x11DFBC53;
word32 g_dw100030A4 = 0x1E00498C;
word32 g_dw100030A8 = 0xDA86C64F;
word32 g_dw100030AC = 0x905A0FE2;
word32 g_dw100030B0 = 0x11DFBC53;
word32 g_dw100030B4 = 0x1E00498C;
word32 g_dw100030B8 = 0xDA86C64F;
word32 g_dw100030BC = 0x905A0FE1;
word32 g_dw100030C0 = 0x11DFBC53;
word32 g_dw100030C4 = 0x1E00498C;
word32 g_dw100030C8 = 0xDA86C64F;
word32 g_dw10003128 = 0x30D5A829;
word32 g_dw1000312C = 0x40267FA4;
word32 g_dw10003130 = 0x5BD7BB83;
word32 g_dw10003134 = 0x9EA94EAE;
word32 g_a10003158[] = 
	{
	};
word32 g_a10003168[] = 
	{
	};
word16 g_w10003338 = 0x0000;
word32 g_dw1000333C = 0xA198529B;
word32 g_dw10003340 = 0x4089730F;
word32 g_dw10003344 = 0x25A146B6;
word32 g_dw10003348 = 0x5E66F557;
Eq_4509 g_t10003714 = 
	{
		0x1AF8D0F5,
		0x48423631,
		0xF00D798B,
		0x4FA7408F,
	};
Eq_4509 g_t10003724 = 
	{
		0xECF0CC88,
		0x48F34648,
		0x84B7F9AF,
		0xD6CA358B,
	};
Eq_4509 g_t10003734 = 
	{
		0x1ABBB96C,
		0x43FEB973,
		0xCFDB0C82,
		0x7DCCA7D3,
	};
Eq_4509 g_t10003744 = 
	{
		0x174BDECA,
		0x4A943B44,
		0xE27C85A7,
		0x33297F7F,
	};
Eq_4509 g_t10003754 = 
	{
		0x34201E5A,
		0x41A3A787,
		0x6DBDA4A5,
		0x4E852ACF,
	};
Eq_4509 g_t10003764 = 
	{
		0x0CCA38EB,
		0x4F4978A9,
		0xA30A3C86,
		0x18C18828,
	};
Eq_4509 g_t10003774 = 
	{
		0x94EA2B94,
		0x49E0E9CC,
		0x64EEFFC0,
		0x905B8FCA,
	};
Eq_4509 g_t10003784 = 
	{
		0x47B0E9C2,
		0x4B5AE86C,
		0x4FCFD1BA,
		0xA9F0EC3D,
	};
Eq_4509 g_t10003794 = 
	{
		0x00000000,
		0x00000000,
		0x000000C0,
		0x46000000,
	};
Eq_4509 g_t100037B4 = 
	{
		0x00000003,
		0x00000000,
		0x000000C0,
		0x46000000,
	};
Eq_17730 g_t10003F20 = 
	{
		0x00000146,
		0x0000,
		0x0000,
		
		{
			0xC0,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x46,
		},
	};
Eq_17730 g_t10003F50 = 
	{
		0xA5DA53F9,
		0xD475,
		0x4080,
		
		{
			0xA1,
			0x20,
			0x91,
			0x0C,
			0x4A,
			0x73,
			0x98,
			0x80,
		},
	};
word32 g_dw10004BA0 = 0x00000038;
word32 g_dw10004BA4 = 0x00000000;
word32 g_dw10004BA8 = 0x000000C0;
word32 g_dw10004BAC = 0x46000000;
Eq_4509 g_t10004BB0 = 
	{
		0x9C29F57E,
		0x4B010947,
		0xA0853EA7,
		0x7DDAAC68,
	};
Eq_4509 g_t10004BD0 = 
	{
		0xAF86E2E0,
		0x4C6AB12D,
		0xAAD75A9C,
		0x901E1065,
	};
word32 g_dw10004C80 = 0xCC35320D;
word32 g_dw10004C84 = 0x42312077;
word32 g_dw10004C88 = 0x1FE9C098;
word32 g_dw10004C8C = 0x1BD107E7;
Eq_4509 g_t10005370 = 
	{
		0xFA6FA76B,
		0x4B1166B7,
		0x1786F195,
		0x16E81811,
	};
Eq_4509 g_t10005380 = 
	{
		0xB53C00B6,
		0x4B789922,
		0xFEDDF4B1,
		0x9BC34D77,
	};
Eq_4509 g_t10005390 = 
	{
		0x2D8DEEB8,
		0x49731322,
		0x82B2F98D,
		0x908246F2,
	};
Eq_4509 g_t100053A0 = 
	{
		0xDF50EA86,
		0x4485B7A9,
		0x0A93048F,
		0x5B6E6849,
	};
Eq_4509 g_t100053B0 = 
	{
		0x82FF5153,
		0x4DF04573,
		0x055E5A94,
		0x225100DD,
	};
Eq_4509 g_t100053C0 = 
	{
		0xDD107CC8,
		0x4E0ED477,
		0x72B00B92,
		0xD4DD3F93,
	};
Eq_4509 g_t100053D0 = 
	{
		0x7C5D038E,
		0x455159F7,
		0x43FAF0A6,
		0x56DC001E,
	};
Eq_4509 g_t100053E0 = 
	{
		0xC8DF4B94,
		0x4ECE3179,
		0x675C8390,
		0x7443644A,
	};
Eq_4509 g_t100053F0 = 
	{
		0x0E532F00,
		0x46A3C69E,
		0xE585A3B7,
		0xA7E6133F,
	};
word32 g_a10005530[] = 
	{
	};
word32 g_a10005540[] = 
	{
	};
word32 g_dw100057B8 = 0x00000000;
word32 g_dw100057BC = 0x00000000;
Eq_17730 g_t100057C0 = 
	{
		0xEC5EC8A9,
		0xC395,
		0x4314,
		
		{
			0x9C,
			0x77,
			0x54,
			0xD7,
			0xA9,
			0x35,
			0xFF,
			0x70,
		},
	};
word32 g_dw100057E0 = 0x6FDDC324;
word32 g_dw100057E4 = 0x4BFE4E03;
word32 g_dw100057E8 = 0x773D85B1;
word32 g_dw100057EC = 0x0FC98D76;
CHAR g_t10006710 = '1';
wchar_t g_str100075E4[] = ",\x00\x00";
Eq_2 g_t100075F8 = 
	{
		false
	};
Eq_2 g_t100075FC = 
	{
		false
	};
Eq_2 g_t10007600 = 
	{
		false
	};
Eq_2 g_t10007604 = 
	{
		false
	};
Eq_2 g_t10007628 = 
	{
		true
	};
Eq_2 g_t1000762C = 
	{
		true
	};
Eq_2 g_t10007630 = 
	{
		true
	};
Eq_2 g_t10007634 = 
	{
		true
	};
Eq_2 g_t10007638 = 
	{
		true
	};
Eq_2 g_t1000763C = 
	{
		true
	};
Eq_2 g_t10007640 = 
	{
		true
	};
Eq_2 g_t10007644 = 
	{
		true
	};
Eq_17730 g_t100076A8 = 
	{
		0x3C708557,
		0xC99D,
		0x4FA3,
		
		{
			0x92,
			0x31,
			0x56,
			0x51,
			0x84,
			0x18,
			0xB4,
			0xE4,
		},
	};
Eq_73760 g_t1000793C = 
	{
		
		{
		},
		0x4967A148,
		0xD7647191,
		0x2085DA55,
	};
Eq_4509 g_t10007A90 = 
	{
		0x90C119AE,
		0x45200F18,
		0x4311F1A1,
		0xE80FA466,
	};
Eq_4509 g_t10007AA0 = 
	{
		0x712DF3E5,
		0x47F5BAF7,
		0x2DDB3191,
		0x932CB0A3,
	};
real64 g_r10007AD0 = 5.0;
Eq_130 g_t10007B59 = 
	{
		0x003D,
	};
Eq_130 g_t10007D2F = 
	{
		0x0020,
	};
Eq_130 g_t10007DC8 = 
	{
		0x006D,
	};
Eq_130 g_t10007E41 = 
	{
		0x0059,
	};
Eq_130 g_t10007EA6 = 
	{
		0x004C,
	};
Eq_130 g_t10007EFE = 
	{
		0x004F,
	};
Eq_130 g_t10007F59 = 
	{
		0x0020,
	};
Eq_130 g_t10008027 = 
	{
		0x005A,
	};
Eq_130 g_t1000808D = 
	{
		0x0073,
	};
Eq_130 g_t1000810C = 
	{
		0x0066,
	};
Eq_130 g_t1000817E = 
	{
		0x0080,
	};
Eq_130 g_t1000820A = 
	{
		0x0063,
	};
Eq_130 g_t10008279 = 
	{
		0x004D,
	};
Eq_130 g_t100082D2 = 
	{
		0x0040,
	};
Eq_130 g_t1000831E = 
	{
		0x004C,
	};
Eq_130 g_t10008376 = 
	{
		0x004D,
	};
Eq_130 g_t100083CF = 
	{
		0x0020,
	};
Eq_130 g_t100083FB = 
	{
		0x0020,
	};
Eq_130 g_t10008662 = 
	{
		0x00E1,
	};
Eq_130 g_t10008A31 = 
	{
		0x006C,
	};
Eq_130 g_t10008B91 = 
	{
		0x003E,
	};
Eq_130 g_t10008BDB = 
	{
		0x0058,
	};
Eq_130 g_t10008C3F = 
	{
		0x011C,
	};
Eq_130 g_t10008D67 = 
	{
		0x0090,
	};
Eq_130 g_t10008E03 = 
	{
		0x0086,
	};
Eq_130 g_t10008E95 = 
	{
		0x0019,
	};
Eq_130 g_t10008EBA = 
	{
		0x005A,
	};
Eq_130 g_t100091DF = 
	{
		0x0070,
	};
Eq_130 g_t10009389 = 
	{
		0x005C,
	};
Eq_130 g_t10009567 = 
	{
		0x0049,
	};
Eq_130 g_t100095BC = 
	{
		0x003F,
	};
Eq_130 g_t10009607 = 
	{
		0x005F,
	};
Eq_130 g_t10009672 = 
	{
		0x0070,
	};
Eq_130 g_t100096EE = 
	{
		0x0063,
	};
Eq_130 g_t1000975D = 
	{
		0x0057,
	};
Eq_130 g_t100097C0 = 
	{
		0x0079,
	};
Eq_130 g_t10009845 = 
	{
		0x009A,
	};
Eq_130 g_t100098EB = 
	{
		0x007F,
	};
Eq_130 g_t10009976 = 
	{
		0x0080,
	};
Eq_130 g_t10009C38 = 
	{
		0x0054,
	};
Eq_130 g_t10009DD5 = 
	{
		0x0058,
	};
Eq_130 g_t10009E39 = 
	{
		0x0067,
	};
Eq_130 g_t10009EAC = 
	{
		0x00C3,
	};
Eq_130 g_t10009F7B = 
	{
		0x007D,
	};
Eq_130 g_t1000A004 = 
	{
		0x003D,
	};
Eq_130 g_t1000A0A5 = 
	{
		0x0048,
	};
Eq_130 g_t1000A0F9 = 
	{
		0x004A,
	};
Eq_130 g_t1000A14F = 
	{
		0x003B,
	};
Eq_130 g_t1000A196 = 
	{
		0x0063,
	};
Eq_130 g_t1000A205 = 
	{
		0x0049,
	};
Eq_130 g_t1000A25A = 
	{
		0x0032,
	};
Eq_130 g_t1000A298 = 
	{
		0x0047,
	};
Eq_130 g_t1000A398 = 
	{
		0x0053,
	};
Eq_130 g_t1000A3F7 = 
	{
		0x0053,
	};
Eq_130 g_t1000A456 = 
	{
		0x0050,
	};
Eq_130 g_t1000A4B2 = 
	{
		0x0043,
	};
Eq_130 g_t1000A856 = 
	{
		0x0043,
	};
Eq_130 g_t1000AEAE = 
	{
		0x0047,
	};
Eq_130 g_t1000AF01 = 
	{
		0x003A,
	};
Eq_130 g_t1000B08F = 
	{
		0x0031,
	};
Eq_130 g_t1000B0CC = 
	{
		0x0039,
	};
Eq_130 g_t1000B111 = 
	{
		0x0035,
	};
Eq_130 g_t1000B152 = 
	{
		0x0052,
	};
Eq_130 g_t1000B1B0 = 
	{
		0x0033,
	};
Eq_130 g_t1000B1EF = 
	{
		0x0076,
	};
Eq_130 g_t1000B271 = 
	{
		0x0039,
	};
Eq_130 g_t1000B2B6 = 
	{
		0x0041,
	};
Eq_130 g_t1000B303 = 
	{
		0x0035,
	};
Eq_130 g_t1000B344 = 
	{
		0x003F,
	};
Eq_130 g_t1000B38F = 
	{
		0x0035,
	};
Eq_130 g_t1000B3D0 = 
	{
		0x003A,
	};
Eq_130 g_t1000B416 = 
	{
		0x0033,
	};
Eq_130 g_t1000B455 = 
	{
		0x0040,
	};
Eq_130 g_t1000B4A1 = 
	{
		0x0033,
	};
Eq_130 g_t1000B4E0 = 
	{
		0x0036,
	};
Eq_130 g_t1000B522 = 
	{
		0x0036,
	};
Eq_130 g_t1000B564 = 
	{
		0x0042,
	};
Eq_130 g_t1000B5FE = 
	{
		0x003E,
	};
Eq_130 g_t1000B648 = 
	{
		0x0039,
	};
Eq_130 g_t1000B68D = 
	{
		0x0038,
	};
Eq_130 g_t1000B6D1 = 
	{
		0x0033,
	};
Eq_130 g_t1000B710 = 
	{
		0x0033,
	};
Eq_130 g_t1000B74F = 
	{
		0x0066,
	};
Eq_130 g_t1000B7C1 = 
	{
		0x0078,
	};
Eq_130 g_t1000B845 = 
	{
		0x0066,
	};
Eq_130 g_t1000B8B7 = 
	{
		0x0056,
	};
Eq_130 g_t1000B919 = 
	{
		0x0055,
	};
Eq_130 g_t1000B97A = 
	{
		0x0059,
	};
Eq_130 g_t1000B9DF = 
	{
		0x0059,
	};
Eq_130 g_t1000BA44 = 
	{
		0x0066,
	};
Eq_130 g_t1000BAB6 = 
	{
		0x0059,
	};
Eq_130 g_t1000BB1B = 
	{
		0x0053,
	};
Eq_130 g_t1000BB7A = 
	{
		0x003D,
	};
Eq_130 g_t1000BBC3 = 
	{
		0x0041,
	};
Eq_130 g_t1000BC10 = 
	{
		0x006A,
	};
Eq_130 g_t1000BC86 = 
	{
		0x003B,
	};
Eq_130 g_t1000BCCD = 
	{
		0x0044,
	};
Eq_130 g_t1000BD1D = 
	{
		0x0040,
	};
Eq_130 g_t1000BE61 = 
	{
		0x008F,
	};
void g_t10015ED0(PTP_CALLBACK_INSTANCE Instance, PVOID Context, PTP_TIMER Timer) = Unexpected function type (fn void (PTP_CALLBACK_INSTANCE, PVOID, PTP_TIMER))
;
struct Eq_454 * g_a10030420[5] = 
	{
		&g_t10001098,
		&g_t1000138C,
		&g_t100013E0,
		&g_t1000145C,
		null,
	};
word32 g_dw10030430 = 0x00000000;
struct Eq_1018 * g_ptr10030434 = null;
Eq_2 g_t10031000 = 
	{
		false
	};
word16 * g_ptr10031004 = &g_w1000BF0C;
word32 g_dw10031018 = 0x00000000;
word32 g_dw1003101C = 0x00000000;
ui32 g_dw10031020 = 0x00000000;
ui32 g_dw10031024 = 0x00000000;
ui32 g_dw10031030 = 0x00000000;
ui32 g_dw10031034 = 0x00000000;
word32 g_dw10031070 = 0x80000000;
Eq_77654 g_t10031074 = 
	{
		0xFFFFFFFF
	};
ui32 g_dw10031078 = 0xBB40E64E;
ui32 g_dw1003107C = 0x44BF19B1;
word32 g_dw10031080 = 0x00000001;
word32 g_dw10031084 = 0xFFFFFFFF;
word32 g_dw10031088 = 0xFFFFFFFF;
word32 g_dw1003108C = 0xFFFFFFFF;
int32 g_dw100310C0 = 0;
word32 g_dw100310C4 = 0x00000000;
struct _RTL_CRITICAL_SECTION g_t100310C8 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00000000,
	};
Eq_2 g_t100310E4 = 
	{
		false
	};
Eq_2 g_t100310E8 = 
	{
		false
	};
Eq_2 g_t100310EC = 
	{
		false
	};
word32 g_dw100310F0 = 0x00000000;
word32 g_dw100310F4 = 0x00000000;
word32 g_dw100310FC = 0x00000000;
word32 g_dw10031100 = 0x00000000;
word32 g_dw10031104 = 0x00000000;
ui32 g_dw10031108 = 0x00000000;
ui32 g_dw1003110C = 0x00000000;
word32 g_dw10031140 = 0x00000000;
struct Eq_80666 * g_ptr100311CC = null;
struct Eq_80663 * g_ptr100311D0 = null;
struct Eq_4 * g_ptr100311D4 = null;
struct Eq_5 * g_ptr100311D8 = null;
Eq_2 g_t100311DC = 
	{
		false
	};
Eq_2 g_t100311E0 = 
	{
		false
	};
Eq_2 g_t100311E4 = 
	{
		false
	};
Eq_2 g_t100311E8 = 
	{
		false
	};
ui32 g_dw100311EC = 0x00000000;
Eq_2 g_t100311F0 = 
	{
		false
	};
Eq_2 g_t100311F4 = 
	{
		false
	};
word32 g_dw100311F8 = 0x00000000;
struct Eq_80656 * g_ptr100311FC = null;
Eq_80672 g_t10031200 = 
	{
		0x00
	};
ptr32 g_ptr10031204 = 0x00000000;
struct Eq_80653 * g_ptr10031208 = null;
ui32 g_dw10031410 = 0x00000000;
word32 g_dw10031418 = 0x00000000;
word32 g_dw1003142C = 0x00000000;
word32 g_dw10031444 = 0x00000000;
word32 g_dw10031460 = 0x00000000;
word32 g_dw10031468 = 0x00000000;
Eq_592 g_t10031478 = 
	{
		0x00000000
	};
word32 g_dw1003147C = 0x00000000;
word32 g_dw10031480 = 0x00000000;
struct Eq_13249 * (* g_ptr100314A8)[] = null;
struct Eq_12955 * g_ptr100314B4 = null;
word32 g_dw100314B8 = 0x00000000;
Eq_2 g_t10031504 = 
	{
		false
	};
word32 g_dw10031508 = 0x00000000;
Eq_2 g_t1003150C = 
	{
		false
	};
word32 g_dw10031510 = 0x00000000;
Eq_2 g_t10031514 = 
	{
		false
	};
word32 g_dw10031518 = 0x00000000;
Eq_2 g_t1003151C = 
	{
		false
	};
Eq_2 g_t10031520 = 
	{
		false
	};
Eq_2 g_t10031524 = 
	{
		false
	};
word32 g_dw10031528 = 0x00000000;
word32 g_dw10031534 = 0x00000000;
word32 g_dw10031538 = 0x00000000;
Eq_2 g_t1003153C = 
	{
		false
	};
word32 g_dw10031540 = 0x00000000;
word32 g_dw10031544 = 0x00000000;
byte g_b10031548 = 0x00;
byte g_b10031549 = 0x00;
byte g_b1003154A = 0x00;
word32 g_dw1003154C = 0x00000000;
Eq_2 g_t10031550 = 
	{
		false
	};
Eq_2 g_t10031554 = 
	{
		false
	};
word32 g_dw1003155C = 0x00000000;
byte g_b10031560 = 0x00;
byte g_b10031580 = 0x00;
int32 g_dw10031588 = 0;
byte g_b10031598 = 0x00;
int32 g_dw1003159C = 0;
ptr32 g_ptr100315A0 = 0x00000000;
ui32 g_dw100315CC = 0x00000000;
word32 g_dw100315D0 = 0x00000000;
word32 g_dw100315D4 = 0x00000000;
Eq_2 g_t100315D8 = 
	{
		false
	};
Eq_2 g_t100315DC = 
	{
		false
	};
word32 g_dw100315E0 = 0x00000000;
Eq_2 g_t100315E4 = 
	{
		false
	};
<anonymous> * g_ptr100323BC = &g_t1002FA30;
Eq_454 g_t10001098 = 
	{
		&g_a10003318,
	};
Eq_454 g_t1000138C = 
	{
		&g_a1000386C,
	};
Eq_454 g_t100013E0 = 
	{
		&g_a100039A4,
	};
Eq_454 g_t1000145C = 
	{
		&g_a10003D44,
	};
word16 g_w1000BF0C = 0x0039;
<anonymous> g_t1002FA30 = <code>;
word32 g_a10003318[] = 
	{
	};
word32 g_a1000386C[] = 
	{
	};
word32 g_a100039A4[] = 
	{
	};
word32 g_a10003D44[] = 
	{
	};

