// authui.c
// Generated by decompiling authui.dll
// using Reko decompiler version 0.7.1.0.

#include "authui.h"

// 10008AF0: Register byte fn10008AF0(Register (ptr (ptr Eq_10)) ecx, Register (ptr Eq_4) edx, Register (ptr Eq_5) ebp, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack byte bArg04)
byte fn10008AF0(Eq_10 * * ecx, Eq_4 * edx, Eq_5 * ebp, Eq_6 * es, Eq_7 * ds, byte bArg04)
{
	ptr32 eax_37;
	struct Eq_10 * eax_24 = *ecx;
	struct Eq_5 * ebp_112 = fp - 0x04;
	ui32 eax_11 = globals->dw100240C4 ^ fp - 0x04;
	ptr32 * esp_113 = fp - 0x1C;
	struct Eq_10 ** edi_107 = ecx;
	ptr32 esi_26 = eax_24->ptr0010;
	if (esi_26 == 0x10009680)
		eax_37 = 0x1001F1FC;
	else
	{
		word32 esp_431;
		word32 edi_432;
		word32 ebp_433;
		byte SCZO_434;
		word32 eax_435;
		byte SZO_436;
		byte C_437;
		word32 ebx_438;
		<anonymous> * esi_439;
		word32 ecx_440;
		byte Z_441;
		byte al_442;
		word32 edx_443;
		struct Eq_46 * es_444;
		struct Eq_47 * ds_445;
		globals->ptr10025410();
		byte SCZO_449;
		byte SZO_451;
		byte C_452;
		word32 ebx_453;
		word32 esi_454;
		word32 ecx_455;
		byte Z_456;
		byte al_457;
		esi_439();
	}
	struct Eq_83 ** ebx_181;
	struct Eq_10 * eax_41 = *edi_107;
	struct Eq_83 ** esi_177 = eax_37 + 0x04;
	ptr32 ebx_43 = eax_41->ptr0018;
	if (ebx_43 == 0x10009690)
		ebx_181 = &globals->ptr1001F20C;
	else
	{
		struct Eq_10 *** esp_386 = esp_113 - 0x04;
		*esp_386 = (struct Eq_10 ***) edi_107;
		word32 esp_389;
		word32 edi_390;
		word32 ebp_391;
		byte SCZO_392;
		word32 eax_393;
		byte SZO_394;
		byte C_395;
		<anonymous> * ebx_396;
		word32 esi_397;
		word32 ecx_398;
		byte Z_399;
		byte al_400;
		word32 edx_401;
		struct Eq_78 * es_402;
		struct Eq_79 * ds_403;
		globals->ptr10025410();
		byte SCZO_407;
		struct Eq_83 ** eax_408;
		byte SZO_409;
		byte C_410;
		word32 ebx_411;
		word32 ecx_413;
		byte Z_414;
		byte al_415;
		ebx_396();
		ebx_181 = eax_408;
	}
	word32 eax_127;
	Eq_258 eax_100;
	if (esi_177 < ebx_181)
	{
		do
		{
			if (*esi_177 != null)
			{
				<anonymous> * eax_206 = *((char *) *edi_107 + 0x0C);
				if (eax_206 == &globals->t100096A0)
					eax_127 = globals->dw10024624;
				else
				{
					struct Eq_10 *** esp_352 = esp_113 - 0x04;
					*esp_352 = (struct Eq_10 ***) edi_107;
					word32 esp_355;
					word32 edi_356;
					word32 ebp_357;
					byte SCZO_358;
					word32 eax_359;
					byte SZO_360;
					byte C_361;
					word32 ebx_362;
					word32 esi_363;
					word32 ecx_364;
					byte Z_365;
					byte al_366;
					word32 edx_367;
					struct Eq_134 * es_368;
					struct Eq_135 * ds_369;
					globals->ptr10025410();
					byte SCZO_373;
					byte SZO_375;
					byte C_376;
					word32 ecx_379;
					byte Z_380;
					byte al_381;
					eax_206();
				}
				if (eax_127 != 0x00)
				{
					if (bArg04 == 0x00)
						goto l10008BA9;
				}
				if (**((char *) *esi_177 + 0x0C) != 0x00)
				{
					struct Eq_10 *** esp_231 = esp_113 - 0x04;
					*esp_231 = (struct Eq_10 ***) edi_107;
					word32 esp_235;
					<anonymous> * edi_236;
					word32 ebp_237;
					byte SCZO_238;
					word32 eax_239;
					byte SZO_240;
					byte C_241;
					word32 ebx_242;
					word32 esi_243;
					word32 ecx_244;
					byte Z_245;
					byte al_246;
					word32 edx_247;
					struct Eq_179 * es_248;
					struct Eq_180 * ds_249;
					globals->ptr10025410();
					ptr32 * esp_250;
					word32 edi_251;
					byte SCZO_253;
					word32 eax_254;
					byte SZO_255;
					byte C_256;
					word32 ecx_259;
					byte Z_260;
					byte al_261;
					edi_236();
					*(esp_250 - 0x04) = eax_254;
					AcquireSRWLockExclusive(*(esp_250 - 0x04));
					word32 * eax_270 = *((char *) *esi_177 + 0x0C);
					esp_113 = esp_250;
					word32 ecx_272 = *eax_270;
					if (ecx_272 == 0x00)
					{
						if (eax_254 != 0x00)
						{
							*(esp_250 - 0x04) = eax_254;
							ReleaseSRWLockExclusive(*(esp_250 - 0x04));
							esp_113 = esp_250;
						}
					}
					else
					{
						*eax_270 = 0x00;
						if (eax_254 != 0x00)
						{
							*(esp_250 - 0x04) = eax_254;
							ReleaseSRWLockExclusive(*(esp_250 - 0x04));
						}
						*(esp_250 - 0x04) = ecx_272;
						Eq_330 eax_306 = DecodePointer(*(esp_250 - 0x04));
						*(esp_250 - 0x04) = (PVOID *) eax_306;
						word32 esp_313;
						<anonymous> * edi_314;
						word32 ebp_315;
						byte SCZO_316;
						word32 eax_317;
						byte SZO_318;
						byte C_319;
						word32 ebx_320;
						word32 esi_321;
						word32 ecx_322;
						byte Z_323;
						byte al_324;
						word32 edx_325;
						struct Eq_357 * es_326;
						struct Eq_358 * ds_327;
						globals->ptr10025410();
						word32 edi_329;
						byte SCZO_331;
						word32 eax_332;
						byte SZO_333;
						byte C_334;
						word32 ecx_337;
						byte Z_338;
						byte al_339;
						edi_314();
					}
					edi_107 = ecx;
				}
			}
			esi_177 = (struct Eq_83 **) ((char *) esi_177 + 0x04);
		} while (esi_177 < ebx_181);
	}
	struct Eq_10 * eax_114 = *edi_107;
	<anonymous> * esi_116 = eax_114->ptr000C;
	if (esi_116 == &globals->t100096A0)
		eax_127 = globals->dw10024624;
	else
	{
		struct Eq_10 *** esp_138 = esp_113 - 0x04;
		*esp_138 = (struct Eq_10 ***) edi_107;
		word32 esp_141;
		word32 edi_142;
		word32 ebp_143;
		byte SCZO_144;
		word32 eax_145;
		byte SZO_146;
		byte C_147;
		word32 ebx_148;
		<anonymous> * esi_149;
		word32 ecx_150;
		byte Z_151;
		byte al_152;
		word32 edx_153;
		struct Eq_242 * es_154;
		struct Eq_243 * ds_155;
		globals->ptr10025410();
		word32 edi_157;
		byte SCZO_159;
		byte SZO_161;
		byte C_162;
		word32 ebx_163;
		word32 esi_164;
		word32 ecx_165;
		byte Z_166;
		byte al_167;
		esi_149();
	}
	if (eax_127 == 0x00)
		eax_100 = DPB(eax_127, 0x01, 0);
	else
	{
l10008BA9:
		eax_100 = DPB(eax_127, 0x00, 0);
	}
	struct Eq_274 * esp_73 = esp_113 + 0x01;
	return (byte) fn1000A130(eax_100, eax_11 ^ fp - 0x04, edx, esp_73->ptr0004, ebp_112, esp_73->t0000, *esp_113, es, ds, ebp);
}

// 10008BC0: void DllGetClassObject(Register (ptr Eq_5) ebp, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack (ptr Eq_4) dwArg04, Stack (ptr ui32) dwArg08, Stack (ptr word32) dwArg0C)
void DllGetClassObject(Eq_5 * ebp, Eq_6 * es, Eq_7 * ds, Eq_4 * dwArg04, ui32 * dwArg08, word32 * dwArg0C)
{
	*dwArg0C = 0x00;
	struct Eq_5 * ebp_173 = fp - 0x04;
	struct Eq_4 * ebx_183 = dwArg04;
	uint32 edi_126 = 0x00;
	union Eq_258 * esp_141 = fp - 0x14;
l10008BE1:
	struct Eq_405 * eax_264 = globals->a10001A70[edi_126];
	struct Eq_4 * edx_112 = dwArg04;
	uint32 esi_265 = 0x0C;
l10008BF0:
	ui32 eax_260;
	Eq_426 ecx_50 = edx_112->dw0000;
	byte cl_51 = (byte) ecx_50;
	if (ecx_50 != eax_264->b0000)
	{
		Eq_403 C_269 = cond(cl_51 - eax_264->b0000);
		if (cl_51 == eax_264->b0000)
		{
			Eq_454 cl_282 = edx_112->dw0001;
			C_269 = cond(cl_282 - eax_264->t0001);
			if (cl_282 == eax_264->t0001)
			{
				Eq_482 cl_288 = edx_112->dw0002;
				C_269 = cond(cl_288 - eax_264->t0002);
				if (cl_288 == eax_264->t0002)
				{
					Eq_494 cl_294 = edx_112->dw0003;
					C_269 = cond(cl_294 - eax_264->t0003);
					if (cl_294 == eax_264->t0003)
						break;
				}
			}
		}
		eax_260 = 0x00 - C_269 | 0x01;
		goto l10008C03;
	}
	edx_112 = edx_112 + 0x01;
	eax_264 = eax_264 + 0x01;
	esi_265 = esi_265 - 0x04;
	if (esi_265 >= 0x00)
		goto l10008BF0;
	eax_260 = 0x00;
l10008C03:
	Eq_258 edi_120;
	if (eax_260 == 0x00)
	{
		word32 edi_129 = globals->a10001A74[edi_126];
		if (edi_129 == 0x00)
			break;
		Eq_258 eax_140 = HeapAlloc(GetProcessHeap(), 0x08, 0x0C);
		esp_141 = fp - 0x14;
		Eq_258 esi_142 = eax_140;
		if (eax_140 != 0x00)
		{
			ptr32 esp_174;
			*eax_140 = &globals->t10001AF4;
			*((word32) eax_140 + 0x04) = 0x01;
			*((word32) eax_140 + 0x08) = edi_129;
			__lock();
			globals->dw10024668 = globals->dw10024668 + 0x01;
			ptr32 edi_158 = **eax_140;
			if (edi_158 == 0x10008D70)
			{
				ebp_173 = fn10008D70(eax_140, dwArg08, dwArg0C);
				esp_174 = fp - 0x14;
			}
			else
			{
				word32 esp_221;
				<anonymous> * edi_222;
				word32 ebp_223;
				word32 ecx_224;
				word32 eax_225;
				byte SZO_226;
				byte C_227;
				word32 ebx_228;
				word32 esi_229;
				word32 edx_230;
				byte SCZO_231;
				byte Z_232;
				byte cl_233;
				byte S_234;
				struct Eq_626 * es_235;
				struct Eq_627 * ds_236;
				globals->ptr10025410();
				word32 edi_238;
				word32 ecx_240;
				byte SZO_242;
				byte C_243;
				word32 ebx_244;
				byte SCZO_247;
				byte Z_248;
				byte cl_249;
				byte S_250;
				edi_222();
			}
			struct Eq_585 * eax_176 = *esi_142;
			union Eq_258 * esp_177 = esp_174 - 0x04;
			*esp_177 = (union Eq_258 *) esi_142;
			edi_120 = eax_140;
			ptr32 ebx_179 = eax_176->ptr0008;
			if (ebx_179 == 0x10008D30)
			{
				fn10008D30(esi_142, dwArg00);
				esp_141 = (union Eq_258 *) ((char *) esp_177 + 0x04);
				ebx_183 = ebp_173->ptr0008;
			}
			else
			{
				word32 esp_185;
				word32 edi_186;
				word32 ebp_187;
				word32 ecx_188;
				word32 eax_189;
				byte SZO_190;
				byte C_191;
				<anonymous> * ebx_192;
				word32 esi_193;
				word32 edx_194;
				byte SCZO_195;
				byte Z_196;
				byte cl_197;
				byte S_198;
				struct Eq_661 * es_199;
				struct Eq_662 * ds_200;
				globals->ptr10025410();
				word32 ecx_204;
				word32 eax_205;
				byte SZO_206;
				byte C_207;
				word32 ebx_208;
				word32 esi_209;
				byte SCZO_211;
				byte Z_212;
				byte cl_213;
				byte S_214;
				ebx_192();
				ebx_183 = ebp_173->ptr0008;
			}
		}
		else
			edi_120 = 0x8007000E;
		goto l10008CAC;
	}
	else
	{
		edi_126 = edi_126 + 0x01;
		if (edi_126 < 0x04)
			goto l10008BE1;
		edi_120 = 0x80040111;
l10008CAC:
		Eq_258 eax_114;
		Eq_258 esi_113 = *esp_141;
		struct Eq_477 * esp_79 = (char *) esp_141 + 0x04;
		if (edi_120 >= 0x00)
			eax_114 = edi_120;
		else
		{
			fn1000D5FD(edx_112, ebx_183, edi_120, es, ds);
			*(esp_79 - 0x04) = (union Eq_258 *) ebp_173->t0010;
			*(esp_79 - 0x08) = ebp_173->dw000C;
			*(esp_79 - 0x0C) = (struct Eq_4 **) ebx_183;
			eax_114 = fn1000D51F(0x1002461C, edx_112, ebp_173, es, ds, dwArg00, dwArg04, dwArg08, out edx_112, out esi_113);
		}
		fn1000A130(eax_114, *(ebp_173 - 0x04) ^ ebp_173, edx_112, esp_79->ptr0004, ebp_173, esi_113, esp_79->ptr0000, es, ds, ebp);
		return;
	}
}

// 10008D30: void fn10008D30(Register Eq_258 esi, Stack Eq_258 dwArg04)
void fn10008D30(Eq_258 esi, Eq_258 dwArg04)
{
	__lock();
	*((word32) dwArg04 + 0x04) = __xadd(*((word32) dwArg04 + 0x04), esi | ~0x00);
	if ((esi | ~0x00) == 0x01 && dwArg04 != 0x00)
	{
		*dwArg04 = &globals->t10001AF4;
		__lock();
		globals->dw10024668 = globals->dw10024668 - 0x01;
		HeapFree(GetProcessHeap(), 0x00, dwArg04);
	}
	return;
}

// 10008D70: Register Eq_258 fn10008D70(Stack Eq_258 dwArg04, Stack (ptr ui32) dwArg08, Stack (ptr word32) dwArg0C)
Eq_258 fn10008D70(Eq_258 dwArg04, ui32 * dwArg08, word32 * dwArg0C)
{
	word32 esp_22;
	word32 edi_23;
	word32 ebp_24;
	SHLWAPI.dll!Ordinal_219();
	return dwArg04;
}

// 100092D0: void DllCanUnloadNow(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register ptr32 esi, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds)
void DllCanUnloadNow(Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, ptr32 esi, ptr32 edi, Eq_6 * es, Eq_7 * ds)
{
	if (globals->dw10024618 > ((fs->ptr002C))[globals->dw1002444C]->dw0004)
	{
		fn1000B57D(edx, ebx, edi, es, ds, &globals->dw10024618);
		if (globals->dw10024618 == ~0x00)
		{
			*(fp - 0x04) = 0x1000CE00;
			globals->ptr10024484 = 0x1002461C;
			globals->ptr1002461C = 0x10001058;
			Eq_258 esi_64;
			struct Eq_4 * ebx_65 = fn1000A45E(edx, ebx, esi, edi, es, ds, dwArg00, out esi_64);
			*(fp - 0x08) = 0x10024618;
			fn1000B53C(edx, ebx_65, ebp, esi_64, edi, es, ds, dwArg00);
		}
	}
	if (globals->dw10024668 <= 0x00)
	{
		*(fp - 0x04) = 0x00;
		if (fn10008AF0(&globals->ptr1002461C, edx, ebp, es, ds, bArg00) != 0x00)
			return;
	}
	return;
}

// 10009330: void fn10009330(Register Eq_842 ecx)
void fn10009330(HMODULE ecx)
{
	DisableThreadLibraryCalls(ecx);
	globals->dw100244F0 = 0x00;
	globals->ptr100244E0 = 0x10024508;
	globals->dw100244F8 = 0x01;
	globals->dw100244FC = 0x00;
	globals->dw10024518 = 0x00;
	globals->ptr10024508 = 0x10024530;
	globals->dw10024520 = 0x01;
	globals->dw10024524 = 0x00;
	globals->dw10024540 = 0x00;
	globals->ptr10024530 = 0x10024558;
	globals->dw10024548 = 0x01;
	globals->dw1002454C = 0x00;
	globals->dw10024568 = 0x00;
	globals->ptr10024558 = 0x10024580;
	globals->dw10024570 = 0x01;
	globals->dw10024574 = 0x00;
	globals->dw10024590 = 0x00;
	globals->ptr10024580 = 0x100245A8;
	globals->dw10024598 = 0x01;
	globals->dw1002459C = 0x00;
	globals->dw100245B8 = 0x00;
	globals->dw100245A8 = 0x00;
	globals->dw100245C0 = 0x01;
	globals->dw100245C4 = 0x00;
	globals->ptr100245D0 = 0x10002CC4;
	globals->ptr100245D4 = 0x10002CB4;
	globals->ptr100245D8 = 268446884;
	globals->ptr100245DC = 268446868;
	globals->ptr100245E0 = 268446852;
	globals->ptr100245E4 = 268446836;
	globals->ptr10024000 = &globals->ptr100244E0;
	ptr32 esp_19 = fp - 0x14;
	struct Eq_944 * esi_21 = &globals->ptr100244E0;
	word32 * edi_23 = &globals->ptr100245D0;
	do
	{
		word32 ecx_56 = *edi_23;
		ptr32 * esp_58 = esp_19 - 0x04;
		*esp_58 = (char *) esi_21 + 0x08;
		*(esp_58 - 0x04) = 0x00;
		*(esp_58 - 0x08) = 0x00;
		*(esp_58 - 0x0C) = fp - 0x0C;
		*(esp_58 - 0x10) = 0x01;
		*(esp_58 - 0x14) = ecx_56;
		*(esp_58 - 0x18) = (struct Eq_944 **) esi_21;
		*(esp_58 - 0x1C) = 0x1000D8D0;
		esi_21->dw0020 = ecx_56;
		word32 ebp_81;
		byte SCZO_82;
		struct Eq_944 ** esi_83;
		word32 ecx_84;
		word32 eax_85;
		byte SZO_86;
		byte C_87;
		byte Z_88;
		ntdll.dll!EtwRegisterTraceGuidsW();
		esi_21 = (struct Eq_944 *) *esi_83;
	} while (esi_21 != null);
	fn100094E0();
	*(esp_19 - 0x04) = 0x100244C8;
	InitializeCriticalSection(*(esp_19 - 0x04));
	globals->t100240D0 = TlsAlloc();
	return;
}

// 100094E0: void fn100094E0()
void fn100094E0()
{
	ui32 eax_4 = globals->dw10024068 | globals->dw1002406C;
	if (eax_4 == 0x00)
	{
		word32 esp_25;
		word32 eax_26;
		byte SZO_27;
		byte C_28;
		byte Z_29;
		ntdll.dll!EtwEventRegister();
	}
	return;
}

// 10009510: Register word32 fn10009510()
word32 fn10009510()
{
	Eq_842 eax_3 = globals->t10024664;
	if (eax_3 != null)
	{
		FreeLibrary(eax_3);
		globals->t10024664 = null;
	}
	DeleteCriticalSection(&globals->t100244C8);
	ptr32 esp_13 = fp - 0x04;
	struct Eq_937 * esi_14 = globals->ptr10024000;
	if (esi_14 != &globals->ptr10024000)
	{
		if (esi_14 != null)
		{
			do
			{
				ui32 edx_52 = esi_14->dw0008;
				ui32 ecx_54 = esi_14->dw000C;
				ui32 eax_55 = edx_52 | ecx_54;
				if (eax_55 != 0x00)
				{
					ui32 * esp_69 = esp_13 - 0x04;
					*esp_69 = ecx_54;
					*(esp_69 - 0x04) = edx_52;
					word32 eax_74;
					byte SZO_75;
					byte C_76;
					byte Z_77;
					byte SCZO_79;
					word32 edx_80;
					word32 ecx_81;
					ntdll.dll!EtwUnregisterTraceGuids();
					esi_14->dw0008 = 0x00;
					esi_14->dw000C = 0x00;
				}
				esi_14 = esi_14->ptr0000;
			} while (esi_14 != null);
		}
		globals->ptr10024000 = &globals->ptr10024000;
	}
	word32 edx_22 = fn100095A0();
	Eq_570 eax_23 = globals->t100240D0;
	ptr32 esp_25 = esp_13 + 0x04;
	if (eax_23 != ~0x00)
	{
		*(esp_25 - 0x04) = (uint32) eax_23;
		TlsFree(*(esp_25 - 0x04));
		globals->t100240D0 = ~0x00;
	}
	return edx_22;
}

// 100095A0: Register ui32 fn100095A0()
ui32 fn100095A0()
{
	ui32 eax_3 = globals->dw10024068;
	ui32 edx_5 = globals->dw1002406C;
	ui32 ecx_6 = eax_3 | edx_5;
	if (ecx_6 == 0x00)
		return edx_5;
	else
	{
		word32 esp_23;
		word32 eax_24;
		word32 ecx_25;
		ui32 edx_26;
		byte SZO_27;
		byte C_28;
		byte Z_29;
		ntdll.dll!EtwEventUnregister();
		globals->dw10024068 = 0x00;
		globals->dw1002406C = 0x00;
		return edx_26;
	}
}

// 10009C02: Register word32 fn10009C02(Register (ptr Eq_4) edx, Register (ptr Eq_5) ebp, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack Eq_842 dwArg04, Stack Eq_569 dwArg08, Stack Eq_570 dwArg0C, Register out ptr32 edxOut)
word32 fn10009C02(Eq_4 * edx, Eq_5 * ebp, Eq_6 * es, Eq_7 * ds, HMODULE dwArg04, HANDLE dwArg08, DWORD dwArg0C, ptr32 & edxOut)
{
	*edxOut = edx;
	Eq_258 edi_135;
	Eq_258 eax_36;
	struct Eq_5 * ebp_136 = fp - 0x04;
	ui32 eax_11 = globals->dw100240C4 ^ fp - 0x04;
	ptr32 * esp_125 = fp - 0x24;
	if (dwArg08 != null)
	{
		edi_135 = 0x01;
		if (dwArg08 != (void *) 0x01)
			goto l10009DEF;
		word32 dwLoc0C_287 = 0x00;
		struct Eq_4 * edx_289 = fs->ptr0018->ptr0004;
		while (true)
		{
			__lock();
			struct Eq_4 * eax_297;
			__cmpxchg(globals->dw1002445C, edx_289, 0x00, out eax_297);
			edx = edx_289;
			*edxOut = edx;
			if (eax_297 == null)
				break;
			if (eax_297 == edx_289)
			{
				dwLoc0C_287 = 0x01;
				break;
			}
			Sleep(1000);
		}
		ptr32 esp_322;
		word32 * esi_316;
		if (globals->dw10024460 != 0x00)
		{
			byte SCZO_412;
			word32 eax_413;
			byte SZO_414;
			byte C_415;
			word32 ebx_416;
			byte Z_418;
			struct Eq_1325 * fs_419;
			word32 ecx_421;
			amsg_exit();
		}
		else
		{
			globals->dw10024460 = 0x01;
			word32 eax_429 = fn1000A0E6(edx_289, (struct Eq_4 *) 0x02, fp - 0x04, 0x01, es, ds, &globals->dw100020C8, &globals->dw100020D4);
			if (eax_429 != 0x00)
			{
l10009D1C:
				esp_125 = fp - 0x24;
				eax_36 = 0x00;
				goto l10009DF1;
			}
			word32 esp_441;
			byte SCZO_444;
			word32 eax_445;
			byte SZO_446;
			byte C_447;
			word32 ebx_448;
			byte Z_450;
			struct Eq_1499 * fs_451;
			word32 ecx_453;
			initterm();
			globals->dw10024460 = 0x02;
			esp_322 = fp - 0x28;
		}
		esp_125 = esp_322 + 0x04;
		if (dwLoc0C_287 == 0x00)
			*esi_316 = 0x00;
		if (globals->dw10024464 != 0x00)
		{
			*(esp_125 - 0x04) = 0x10024464;
			word32 eax_353 = fn1000A1A0(dwArg00, out edx);
			if (eax_353 != 0x00)
			{
				*(esp_125 - 0x04) = (uint32) dwArg0C;
				*(esp_125 - 0x08) = 0x02;
				*(esp_125 - 0x0C) = (HMODULE *) dwArg04;
				word32 esp_371;
				word32 edi_372;
				word32 ebp_373;
				byte SCZO_374;
				word32 eax_375;
				byte SZO_376;
				byte C_377;
				word32 ebx_378;
				<anonymous> * esi_379;
				byte Z_380;
				struct Eq_1473 * fs_381;
				word32 edx_382;
				word32 ecx_383;
				struct Eq_1476 * es_384;
				struct Eq_1477 * ds_385;
				globals->ptr10025410();
				byte SCZO_389;
				word32 eax_390;
				byte SZO_391;
				byte C_392;
				word32 ebx_393;
				word32 esi_394;
				byte Z_395;
				struct Eq_1487 * fs_396;
				word32 ecx_398;
				esi_379();
			}
		}
		globals->dw100240E0 = globals->dw100240E0 + 0x01;
		goto l10009DEF;
	}
	else
	{
		int32 eax_95 = globals->dw100240E0;
		if (eax_95 > 0x00)
		{
			globals->dw100240E0 = eax_95 - 0x01;
			struct Eq_4 * edx_110 = fs->ptr0018->ptr0004;
			__lock();
			struct Eq_4 * eax_114;
			__cmpxchg(globals->dw1002445C, edx_110, 0x00, out eax_114);
			word32 dwLoc0C_109 = 0x00;
			while (true)
			{
				edx = edx_110;
				*edxOut = edx;
				esp_125 = fp - 0x24;
				if (eax_114 == null)
					break;
				if (eax_114 == edx_110)
				{
					dwLoc0C_109 = 0x01;
					break;
				}
				Sleep(1000);
				__lock();
				__cmpxchg(globals->dw1002445C, edx_110, 0x00, out eax_114);
			}
			if (globals->dw10024460 != 0x02)
			{
				word32 esp_134;
				byte SCZO_137;
				word32 eax_138;
				byte SZO_139;
				byte C_140;
				word32 ebx_141;
				word32 esi_142;
				byte Z_143;
				struct Eq_1291 * fs_144;
				word32 ecx_146;
				amsg_exit();
				esp_125 = fp - 0x24;
			}
			else
			{
				struct Eq_4 * eax_151 = globals->ptr10024458;
				struct Eq_4 * dwLoc18_152 = eax_151;
				if (eax_151 != null)
				{
					struct Eq_4 * esi_181 = globals->ptr10024454;
					struct Eq_4 * dwLoc10_183 = esi_181;
					while (true)
					{
						esi_181 = esi_181 - 0x04;
						if (esi_181 < eax_151)
							break;
						<anonymous> * ecx_203 = esi_181->dw0000;
						if (ecx_203 == null)
							continue;
						esi_181->dw0000 = 0x00;
						word32 esp_209;
						word32 edi_210;
						word32 ebp_211;
						byte SCZO_212;
						word32 eax_213;
						byte SZO_214;
						byte C_215;
						word32 ebx_216;
						word32 esi_217;
						byte Z_218;
						struct Eq_1393 * fs_219;
						word32 edx_220;
						word32 ecx_221;
						struct Eq_1396 * es_222;
						struct Eq_1397 * ds_223;
						globals->ptr10025410();
						struct Eq_4 * edi_225;
						byte SCZO_227;
						word32 eax_228;
						byte SZO_229;
						byte C_230;
						word32 ebx_231;
						byte Z_233;
						struct Eq_1407 * fs_234;
						word32 edx_235;
						word32 ecx_236;
						ecx_203();
						edx = globals->ptr10024458;
						*edxOut = edx;
						struct Eq_4 * ecx_240 = globals->ptr10024454;
						if (edi_225 == edx)
						{
							eax_151 = dwLoc18_152;
							if (dwLoc10_183 == ecx_240)
								continue;
						}
						eax_151 = edx;
						dwLoc10_183 = ecx_240;
						dwLoc18_152 = edx;
						esi_181 = ecx_240;
					}
					struct Eq_4 ** esp_253 = esp_125 - 0x04;
					*esp_253 = (struct Eq_4 **) eax_151;
					free(*esp_253);
					globals->ptr10024454 = null;
					globals->ptr10024458 = null;
					esp_125 = (ptr32 *) ((char *) esp_253 + 0x04);
				}
				globals->dw10024460 = 0x00;
				edi_135 = 0x01;
				if (dwLoc0C_109 == 0x00)
					globals->dw1002445C = 0x00;
			}
l10009DEF:
			eax_36 = edi_135;
l10009DF1:
			struct Eq_1520 * esp_41 = esp_125 + 0x01;
			return fn1000A130(eax_36, eax_11 ^ fp - 0x04, edx, esp_41->ptr0004, ebp_136, esp_41->t0000, *esp_125, es, ds, ebp);
		}
		goto l10009D1C;
	}
}

// 10009E10: Register Eq_258 DllMain(Stack Eq_569 hModule, Stack Eq_570 dwReason, Stack Eq_258 lpReserved)
Eq_258 DllMain(HANDLE hModule, DWORD dwReason, Eq_258 lpReserved)
{
	ptr32 edi_12 = edi;
	if (dwReason == 0x01)
		fn1000A293();
	struct Eq_5 * ebp_158 = fn1000A33C(ebx, esi, edi, dwLoc0C, 268562376, 0x30);
	*(ebp_158 - 0x20) = 0x01;
	*(ebp_158 - 0x04) = 0x00;
	ptr32 esp_23 = fp - 0x08;
	Eq_258 esi_102 = 0x00;
	uint32 eax_32 = ebp_158->dw000C;
	if (eax_32 <= 0x01)
		globals->dw100240C0 = eax_32;
	if (ebp_158->dw000C == 0x00 && globals->dw100240E0 == 0x00)
	{
		*(ebp_158 - 0x20) = 0x00;
		goto l1000A0BE;
	}
	uint32 eax_57 = ebp_158->dw000C;
	if (eax_57 == 0x01 || eax_57 == 0x02)
	{
		edi_12 = globals->ptr10024468;
		if (edi_12 != 0x00)
		{
			*(ebp_158 - 0x04) = 0x01;
			if (ebp_158->dw000C == 0x01)
				globals->dw100240E4 = 0x01;
			*(fp - 0x0C) = (union Eq_258 *) ebp_158->t0010;
			*(fp - 0x10) = ebp_158->dw000C;
			*(fp - 0x14) = (struct Eq_4 **) ebp_158->ptr0008;
			word32 esp_302;
			<anonymous> * edi_303;
			word32 ebp_304;
			byte SCZO_305;
			byte Z_306;
			word32 esi_307;
			byte SZO_308;
			byte C_309;
			word32 eax_310;
			byte CZ_311;
			word32 ecx_312;
			word32 ebx_313;
			word32 edx_314;
			struct Eq_1769 * es_315;
			struct Eq_1770 * ds_316;
			globals->ptr10025410();
			byte SCZO_320;
			byte Z_321;
			byte SZO_323;
			byte C_324;
			word32 eax_325;
			byte CZ_326;
			word32 ecx_327;
			edi_303();
			*(ebp_158 - 0x20) = eax_325;
			*(ebp_158 - 0x04) = 0x00;
		}
		if (*(ebp_158 - 0x20) == 0x00)
		{
l1000A0BE:
			*(ebp_158 - 0x04) = ~0x01;
			fn1000A0D5(ebp_158);
			word32 ebx_54;
			word32 esi_55;
			return fn1000A384(*(ebp_158 - 0x20), edx, ebx, ebp_158, esi_102, edi_12, es, ds, 0x30, dwArg00, hModule, dwReason, lpReserved, out ebx_54, out esi_55);
		}
		*(ebp_158 - 0x04) = 0x02;
		union Eq_258 * esp_274 = esp_23 - 0x04;
		*esp_274 = (union Eq_258 *) ebp_158->t0010;
		*(esp_274 - 0x04) = ebp_158->dw000C;
		*(esp_274 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
		*(ebp_158 - 0x20) = fn10009C02(edx, ebp_158, es, ds, dwArg00, hModule, dwReason, out edx);
		esp_23 = (char *) esp_274 + 0x04;
		*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
		if (*(ebp_158 - 0x20) == 0x00)
			goto l1000A0BE;
	}
	*(ebp_158 - 0x04) = 0x03;
	union Eq_258 * esp_74 = esp_23 - 0x04;
	*esp_74 = (union Eq_258 *) ebp_158->t0010;
	*(esp_74 - 0x04) = ebp_158->dw000C;
	*(esp_74 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
	word32 eax_86 = fn1000BA48(edx, ebx, es, ds, dwArg00, hModule, out edx, out ebp_158, out esi_102, out edi_12);
	*(ebp_158 - 0x20) = eax_86;
	ptr32 esp_100 = (char *) esp_74 + 0x04;
	*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
	if (ebp_158->dw000C == 0x01 && *(ebp_158 - 0x20) == 0x00)
	{
		*(ebp_158 - 0x04) = 0x04;
		*esp_74 = (union Eq_258 *) esi_102;
		*(esp_74 - 0x04) = (union Eq_258 *) esi_102;
		*(esp_74 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
		struct Eq_4 * edx_185;
		word32 edi_188;
		fn1000BA48(edx, ebx, es, ds, dwArg00, hModule, out edx_185, out ebp_158, out esi_102, out edi_188);
		*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
		*(ebp_158 - 0x04) = 0x05;
		*esp_74 = (union Eq_258 *) esi_102;
		*(esp_74 - 0x04) = (union Eq_258 *) esi_102;
		*(esp_74 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
		word32 eax_201 = fn10009C02(edx_185, ebp_158, es, ds, dwArg00, hModule, dwReason, out edx);
		esp_100 = (char *) esp_74 + 0x04;
		*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
		edi_12 = globals->ptr10024468;
		if (edi_12 != 0x00)
		{
			*(ebp_158 - 0x04) = 0x06;
			*esp_74 = (union Eq_258 *) esi_102;
			*(esp_74 - 0x04) = (union Eq_258 *) esi_102;
			*(esp_74 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
			word32 esp_217;
			<anonymous> * edi_218;
			word32 ebp_219;
			byte SCZO_220;
			byte Z_221;
			word32 esi_222;
			byte SZO_223;
			byte C_224;
			word32 eax_225;
			byte CZ_226;
			word32 ecx_227;
			word32 ebx_228;
			word32 edx_229;
			struct Eq_2029 * es_230;
			struct Eq_2030 * ds_231;
			globals->ptr10025410();
			byte SCZO_235;
			byte Z_236;
			byte SZO_238;
			byte C_239;
			word32 eax_240;
			byte CZ_241;
			word32 ecx_242;
			edi_218();
			*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
		}
	}
	uint32 eax_103 = ebp_158->dw000C;
	if (eax_103 == 0x00 || eax_103 == 0x03)
	{
		*(ebp_158 - 0x04) = 0x07;
		union Eq_258 * esp_111 = esp_100 - 0x04;
		*esp_111 = (union Eq_258 *) ebp_158->t0010;
		*(esp_111 - 0x04) = ebp_158->dw000C;
		*(esp_111 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
		word32 eax_120 = fn10009C02(edx, ebp_158, es, ds, dwArg00, hModule, dwReason, out edx);
		*(ebp_158 - 0x20) = eax_120;
		*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
		edi_12 = globals->ptr10024468;
		if (edi_12 != 0x00 && globals->dw100240E4 != 0x00)
		{
			*(ebp_158 - 0x04) = 0x08;
			*esp_111 = (union Eq_258 *) ebp_158->t0010;
			*(esp_111 - 0x04) = ebp_158->dw000C;
			*(esp_111 - 0x08) = (struct Eq_4 **) ebp_158->ptr0008;
			word32 esp_141;
			<anonymous> * edi_142;
			word32 ebp_143;
			byte SCZO_144;
			byte Z_145;
			word32 esi_146;
			byte SZO_147;
			byte C_148;
			word32 eax_149;
			byte CZ_150;
			word32 ecx_151;
			word32 ebx_152;
			word32 edx_153;
			struct Eq_2090 * es_154;
			struct Eq_2091 * ds_155;
			globals->ptr10025410();
			word32 esp_156;
			byte SCZO_159;
			byte Z_160;
			byte SZO_162;
			byte C_163;
			word32 eax_164;
			byte CZ_165;
			word32 ecx_166;
			edi_142();
			*(ebp_158 - 0x20) = eax_164;
			*(ebp_158 - 0x04) = (union Eq_258 *) esi_102;
		}
	}
	goto l1000A0BE;
}

// 1000A0D5: void fn1000A0D5(Register (ptr Eq_5) ebp)
void fn1000A0D5(Eq_5 * ebp)
{
	if (ebp->dw000C <= 0x01)
		globals->dw100240C0 = ~0x00;
	return;
}

// 1000A0E6: Register Eq_258 fn1000A0E6(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack (ptr word32) dwArg04, Stack (ptr word32) dwArg08)
Eq_258 fn1000A0E6(Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, ptr32 edi, Eq_6 * es, Eq_7 * ds, word32 * dwArg04, word32 * dwArg08)
{
	ptr32 edi_3 = edi;
	struct Eq_5 * ebp_118 = fp - 0x04;
	ui32 eax_13 = globals->dw100240C4 ^ fp - 0x04;
	union Eq_258 * esp_15 = fp - 0x0C;
	word32 * esi_123 = dwArg04;
	Eq_258 eax_120 = 0x00;
	if (dwArg04 < dwArg08)
	{
		ptr32 * esp_116 = fp - 0x10;
		if (eax_120 == 0x00)
		{
			word32 edi_82 = *esi_123;
			if (edi_82 != 0x00)
			{
				word32 esp_102;
				<anonymous> * edi_103;
				word32 ebp_104;
				word32 ecx_105;
				word32 eax_106;
				byte SZO_107;
				byte C_108;
				word32 esi_109;
				byte SCZO_110;
				byte Z_111;
				word32 edx_112;
				word32 ebx_113;
				struct Eq_2174 * es_114;
				struct Eq_2175 * ds_115;
				globals->ptr10025410();
				word32 edi_117;
				word32 ecx_119;
				byte SZO_121;
				byte C_122;
				byte SCZO_124;
				byte Z_125;
				edi_103();
			}
			esi_123 = esi_123 + 0x01;
			if (esi_123 < dwArg08)
				goto l1000A102;
		}
		edi_3 = *esp_116;
		esp_15 = (union Eq_258 *) (esp_116 + 0x01);
	}
	return fn1000A130(eax_120, eax_13 ^ fp - 0x04, edx, ebx, ebp_118, *esp_15, edi_3, es, ds, ebp);
}

// 1000A130: Register Eq_258 fn1000A130(Register Eq_258 eax, Register ui32 ecx, Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register Eq_258 esi, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack (ptr Eq_5) dwArg00)
Eq_258 fn1000A130(Eq_258 eax, ui32 ecx, Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, Eq_258 esi, ptr32 edi, Eq_6 * es, Eq_7 * ds, Eq_5 * dwArg00)
{
	if (ecx != globals->dw100240C4)
	{
		globals->t100241E8 = eax;
		globals->dw100241E4 = ecx;
		globals->ptr100241E0 = edx;
		globals->ptr100241DC = ebx;
		globals->t100241D8 = esi;
		globals->ptr100241D4 = edi;
		globals->ptr10024200 = ss;
		globals->ptr100241F4 = cs;
		globals->ptr100241D0 = ds;
		globals->ptr100241CC = es;
		globals->ptr100241C8 = fs;
		globals->ptr100241C4 = gs;
		globals->t100241F8 = cond(fp - 808);
		globals->ptr100241EC = ebp;
		globals->ptr100241F0 = dwArg00;
		globals->ptr100241FC = fp + 0x04;
		globals->dw10024138 = 0x00010001;
		globals->ptr100240F4 = globals->ptr100241F0;
		globals->dw100240E8 = 0xC0000409;
		globals->dw100240EC = 0x01;
		globals->dw100240F8 = 0x03;
		globals->dw100240FC = 0x02;
		globals->dw10024100 = globals->dw100240C4;
		globals->dw10024104 = globals->dw100240C8;
		return fn1000A475(&globals->t10001088);
	}
	else
		return eax;
}

// 1000A150: Register (ptr Eq_2263) fn1000A150(Stack (ptr Eq_2264) dwArg04, Stack uint32 dwArg08, Register out ptr32 edxOut)
Eq_2263 * fn1000A150(Eq_2264 * dwArg04, uint32 dwArg08, ptr32 & edxOut)
{
	struct Eq_2267 * ecx_21 = dwArg04 + dwArg04->dw003C / 0x0040;
	uint32 edx_10;
	*edxOut = 0x00;
	uint32 ebx_23 = (word32) ecx_21->w0006;
	struct Eq_2263 * eax_25 = &(ecx_21 + ((word32) ecx_21->w0014 + 0x18) / 22)->w0006 + 0x03;
	if (ebx_23 != 0x00)
	{
		do
		{
			uint32 esi_58 = eax_25->dw0000;
			if (dwArg08 >= esi_58 && dwArg08 < eax_25->dw0008 + esi_58)
				return eax_25;
			edx_10 = edx_10 + 0x01;
			*edxOut = edx_10;
			eax_25 = eax_25 + 0x01;
		} while (edx_10 < ebx_23);
	}
	eax_25 = null;
	return eax_25;
}

// 1000A1A0: Register ui32 fn1000A1A0(Stack ui32 dwArg04, Register out ptr32 edxOut)
ui32 fn1000A1A0(ui32 dwArg04, ptr32 & edxOut)
{
	ptr32 eax_16 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	word32 edx_43;
	if (fn1000A260(&globals->t10000000, out edx_43) != 0x00)
	{
		word32 edx_96;
		struct Eq_2333 * eax_97 = fn1000A150(&globals->t10000000, dwArg04 - 0x10000000, out edx_96);
		if (eax_97 != null)
		{
			uint32 eax_104 = ~(eax_97->dw0024 >> 0x1F);
			fs->ptr0000 = eax_16;
			return eax_104 & 0x01;
		}
	}
	fs->ptr0000 = eax_16;
	return 0x00;
}

// 1000A260: Register word32 fn1000A260(Stack (ptr Eq_2322) dwArg04, Register out ptr32 edxOut)
word32 fn1000A260(Eq_2322 * dwArg04, ptr32 & edxOut)
{
	*edxOut = edx;
	if (dwArg04->w0000 == 23117)
	{
		struct Eq_2362 * ecx_38 = dwArg04 + dwArg04->dw003C / 0x0040;
		word32 eax_40 = 0x00;
		if (ecx_38->dw0000 == 0x4550)
		{
			word32 edx_54;
			*edxOut = 0x010B;
			eax_40 = (word32) (ecx_38->w0018 == 0x010B);
		}
		return eax_40;
	}
	else
		return 0x00;
}

// 1000A293: void fn1000A293()
void fn1000A293()
{
	ui32 eax_18 = globals->dw100240C4;
	if (eax_18 != 0xBB40E64E && (eax_18 & 0xFFFF0000) != 0x00)
		globals->dw100240C8 = ~eax_18;
	else
	{
		GetSystemTimeAsFileTime(fp - 0x10);
		ui32 eax_62 = GetTickCount() ^ (((dwLoc0C & 0x00 ^ dwLoc10 & 0x00) ^ GetCurrentProcessId()) ^ GetCurrentThreadId()) ^ fp - 0x08;
		QueryPerformanceCounter(fp - 0x18);
		ui32 ecx_74 = eax_62 ^ (dwLoc14 ^ dwLoc18);
		if (ecx_74 == 0xBB40E64E || (globals->dw100240C4 & 0xFFFF0000) == 0x00)
			ecx_74 = ~0x44BF19B0;
		globals->dw100240C4 = ecx_74;
		globals->dw100240C8 = ~ecx_74;
	}
	return;
}

// 1000A33C: Register ptr32 fn1000A33C(Register (ptr Eq_4) ebx, Register ptr32 esi, Register ptr32 edi, Stack word32 dwArg00, Stack word32 dwArg04, Stack ui32 dwArg08)
ptr32 fn1000A33C(Eq_4 * ebx, ptr32 esi, ptr32 edi, word32 dwArg00, word32 dwArg04, ui32 dwArg08)
{
	ptr32 esp_14 = fp - 0x08 - dwArg08;
	*(esp_14 - 0x04) = (struct Eq_4 **) ebx;
	*(esp_14 - 0x08) = esi;
	*(esp_14 - 0x0C) = edi;
	*(esp_14 - 0x10) = globals->dw100240C4 ^ fp + 0x08;
	*(esp_14 - 0x14) = dwArg00;
	fs->ptr0000 = fp - 0x08;
	return fp + 0x08;
}

// 1000A384: Register Eq_258 fn1000A384(Register Eq_258 eax, Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register Eq_258 esi, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack word32 dwArg00, Stack Eq_842 dwArg04, Stack Eq_569 dwArg08, Stack Eq_570 dwArg0C, Stack Eq_258 dwArg10, Register out ptr32 ebxOut, Register out ptr32 esiOut)
Eq_258 fn1000A384(Eq_258 eax, Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, Eq_258 esi, ptr32 edi, Eq_6 * es, Eq_7 * ds, word32 dwArg00, HMODULE dwArg04, HANDLE dwArg08, DWORD dwArg0C, Eq_258 dwArg10, ptr32 & ebxOut, ptr32 & esiOut)
{
	Eq_258 eax_16 = fn1000A130(eax, *(ebp - 0x1C) ^ ebp, edx, ebx, ebp, esi, edi, es, ds, dwLoc04);
	fs->dw0000 = *(ebp - 0x10);
	ebp->dw0000 = dwArg00;
	word32 esi_30;
	*esiOut = dwArg0C;
	word32 ebx_33;
	*ebxOut = dwArg10;
	return eax_16;
}

// 1000A3C5: Register word32 fn1000A3C5(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register ptr32 esi, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Register out ptr32 ebxOut, Register out ptr32 esiOut)
word32 fn1000A3C5(Eq_4 * edx, Eq_4 * ebx, ptr32 esi, ptr32 edi, Eq_6 * es, Eq_7 * ds, ptr32 & ebxOut, ptr32 & esiOut)
{
	Eq_258 eax_127;
	Eq_258 esi_120;
	struct Eq_4 * ebx_114;
	struct Eq_5 * ebp_105;
	struct Eq_4 * edx_113;
	ptr32 edi_115;
	struct Eq_6 * es_116;
	struct Eq_7 * ds_117;
	struct Eq_5 * ebp_10 = fn1000A33C(ebx, esi, edi, dwLoc0C, 0x1001F068, 0x18);
	*(ebp_10 - 0x28) = *(ebp_10 - 0x28) & 0x00;
	struct Eq_4 * eax_15 = globals->ptr10024458;
	*(ebp_10 - 0x20) = (struct Eq_4 **) eax_15;
	if (eax_15 == (struct Eq_4 *) ~0x00)
	{
		*(fp - 0x0C) = (struct Eq_4 **) ebp_10->ptr0008;
		union Eq_258 * esp_51;
		byte SZO_53;
		byte C_54;
		word32 eax_55;
		byte SCZO_56;
		byte Z_57;
		word32 ecx_59;
		globals->ptr10025410();
		eax_127 = _onexit(*esp_51);
	}
	else
	{
		*(fp - 0x0C) = 0x08;
		ptr32 * esp_71;
		struct Eq_2571 * ebp_72;
		byte SZO_73;
		byte C_74;
		word32 eax_75;
		byte SCZO_76;
		byte Z_77;
		word32 esi_78;
		word32 ecx_79;
		word32 edx_80;
		word32 ebx_81;
		word32 edi_82;
		struct Eq_2582 * es_83;
		struct Eq_2583 * ds_84;
		lock();
		*(ebp_72 - 0x04) = *(ebp_72 - 0x04) & 0x00;
		*(ebp_72 - 0x20) = (struct Eq_4 **) globals->ptr10024458;
		*(ebp_72 - 0x24) = (struct Eq_4 **) globals->ptr10024454;
		*esp_71 = ebp_72 - 0x24;
		*(esp_71 - 0x04) = ebp_72 - 0x20;
		*(esp_71 - 0x08) = ebp_72->dw0008;
		word32 esp_104;
		byte SZO_106;
		byte C_107;
		Eq_258 eax_108;
		byte SCZO_109;
		byte Z_110;
		word32 esi_111;
		word32 ecx_112;
		_dllonexit();
		*(ebp_105 - 0x28) = (union Eq_258 *) eax_108;
		globals->ptr10024458 = (struct Eq_4 *) *(ebp_105 - 0x20);
		globals->ptr10024454 = (struct Eq_4 *) *(ebp_105 - 0x24);
		*(ebp_105 - 0x04) = ~0x01;
		fn1000A455();
		esi_120 = eax_108;
		eax_127 = eax_108;
	}
	word32 ebx_37;
	word32 esi_38;
	return fn1000A384(eax_127, edx_113, ebx_114, ebp_105, esi_120, edi_115, es_116, ds_117, 0x18, dwArg00, dwArg04, dwArg08, dwArg0C, out ebx_37, out esi_38);
}

// 1000A455: void fn1000A455()
void fn1000A455()
{
	word32 esp_4;
	word32 ecx_5;
	unlock();
	return;
}

// 1000A45E: Register (ptr Eq_4) fn1000A45E(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register ptr32 esi, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack (ptr word32) dwArg04, Register out ptr32 esiOut)
Eq_4 * fn1000A45E(Eq_4 * edx, Eq_4 * ebx, ptr32 esi, ptr32 edi, Eq_6 * es, Eq_7 * ds, word32 * dwArg04, ptr32 & esiOut)
{
	struct Eq_4 * ebx_17;
	word32 esi_18;
	fn1000A3C5(edx, ebx, esi, edi, es, ds, out ebx_17, out esi_18);
	return ebx_17;
}

// 1000A475: Register Eq_258 fn1000A475(Stack (ptr Eq_2260) dwArg04)
Eq_258 fn1000A475(_EXCEPTION_POINTERS * dwArg04)
{
	SetUnhandledExceptionFilter(null);
	UnhandledExceptionFilter(dwArg04);
	return TerminateProcess(GetCurrentProcess(), 0xC0000409);
}

// 1000B53C: void fn1000B53C(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register Eq_258 esi, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack (ptr word32) dwArg04)
void fn1000B53C(Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, Eq_258 esi, ptr32 edi, Eq_6 * es, Eq_7 * ds, word32 * dwArg04)
{
	fn1000B5C5();
	word32 ecx_9 = globals->dw100240CC;
	globals->dw100240CC = ecx_9 + 0x01;
	*dwArg04 = ecx_9 + 0x01;
	struct Eq_2749 * ecx_19 = fs->ptr002C[globals->dw1002444C];
	ecx_19->dw0004 = globals->dw100240CC;
	fn1000B631();
	Eq_258 eax_115;
	*(fp - 0x04) = (struct Eq_5 **) ebp;
	*(fp - 0x08) = (struct Eq_2749 **) ecx_19;
	*(fp - 0x08) = globals->dw100240C4 ^ fp - 0x04;
	ptr32 edi_25 = edi;
	struct Eq_5 * ebp_28 = fp - 0x04;
	Eq_569 eax_34 = globals->t1002443C;
	if (eax_34 == null)
	{
		*(fp - 0x0C) = (union Eq_258 *) esi;
		ui32 esi_60 = globals->dw100240C4;
		byte cl_64 = (byte) (esi_60 & 0x1F);
		word32 esi_67 = __ror(esi_60 ^ globals->dw10024444, cl_64);
		*(fp - 0x10) = 0x10024438;
		word32 esp_76;
		word32 edi_77;
		word32 ebp_78;
		word32 ecx_79;
		word32 eax_80;
		byte SZO_81;
		struct Eq_2853 * fs_82;
		byte C_83;
		byte Z_84;
		<anonymous> * esi_85;
		byte cl_86;
		word32 edx_87;
		word32 ebx_88;
		struct Eq_2860 * es_89;
		struct Eq_2861 * ds_90;
		globals->ptr10025410();
		union Eq_258 * esp_91;
		word32 ecx_94;
		byte SZO_96;
		struct Eq_2867 * fs_97;
		byte C_98;
		byte Z_99;
		word32 esi_100;
		byte cl_101;
		esi_85();
		esi = *esp_91;
	}
	else
	{
		*(fp - 0x0C) = (HANDLE *) eax_34;
		SetEvent(*(fp - 0x0C));
		*(fp - 0x0C) = (HANDLE *) globals->t1002443C;
		eax_115 = ResetEvent(*(fp - 0x0C));
	}
	fn1000A130(eax_115, *(ebp_28 - 0x04) ^ ebp_28, edx, ebx, ebp_28, esi, edi_25, es, ds, ebp);
	return;
}

// 1000B57D: void fn1000B57D(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack (ptr ui32) dwArg04)
void fn1000B57D(Eq_4 * edx, Eq_4 * ebx, ptr32 edi, Eq_6 * es, Eq_7 * ds, ui32 * dwArg04)
{
	fn1000B5C5();
	ui32 * esi_12 = dwArg04;
	while (*esi_12 != 0x00)
	{
		if (*esi_12 != ~0x00)
		{
			fs->ptr002C[globals->dw1002444C]->dw0004 = globals->dw100240CC;
			goto l1000B5BE;
		}
		esi_12 = fn1000B63D(edx, ebx, fp - 0x04, edi, es, ds, 100);
	}
	*esi_12 = *esi_12 | ~0x00;
l1000B5BE:
	fn1000B631();
	return;
}

// 1000B5C5: void fn1000B5C5()
void fn1000B5C5()
{
	EnterCriticalSection(&globals->t10024420);
	return;
}

// 1000B631: void fn1000B631()
void fn1000B631()
{
fn1000B631_entry:
l1000B631:
fn1000B631_exit:
}

// 1000B63D: Register Eq_258 fn1000B63D(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register ptr32 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack Eq_570 dwArg04)
Eq_258 fn1000B63D(Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, ptr32 edi, Eq_6 * es, Eq_7 * ds, DWORD dwArg04)
{
	union Eq_258 * esp_114;
	Eq_258 eax_104;
	ptr32 edi_3 = edi;
	struct Eq_5 * ebp_34 = fp - 0x04;
	ui32 eax_13 = globals->dw100240C4 ^ fp - 0x04;
	if (globals->t1002443C == null)
	{
		ui32 esi_46 = globals->dw100240C4;
		byte cl_54 = (byte) (esi_46 & 0x1F);
		word32 esi_57 = __ror(esi_46 ^ globals->dw10024440, cl_54);
		word32 esp_68;
		word32 edi_69;
		word32 ebp_70;
		word32 ecx_71;
		word32 eax_72;
		byte SZO_73;
		byte C_74;
		byte SCZO_75;
		<anonymous> * esi_76;
		byte Z_77;
		byte cl_78;
		byte al_79;
		word32 edx_80;
		word32 ebx_81;
		struct Eq_3001 * es_82;
		struct Eq_3002 * ds_83;
		globals->ptr10025410();
		word32 ecx_87;
		word32 eax_88;
		byte SZO_89;
		byte C_90;
		byte SCZO_91;
		word32 esi_92;
		byte Z_93;
		byte cl_94;
		byte al_95;
		esi_76();
		eax_104 = DPB(eax_88, eax_88 != 0x00, 0);
	}
	else
	{
		fn1000B631();
		Eq_570 eax_113 = WaitForSingleObjectEx(globals->t1002443C, dwArg04, 0x00);
		fn1000B5C5();
		esp_114 = fp - 0x0C;
		eax_104 = DPB(eax_113, eax_113 == 0x00, 0);
	}
	Eq_258 esi_40 = *esp_114;
	fn1000A130(eax_104, eax_13 ^ fp - 0x04, edx, ebx, ebp_34, esi_40, edi_3, es, ds, ebp);
	return esi_40;
}

// 1000BA48: Register word32 fn1000BA48(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack Eq_842 dwArg04, Stack Eq_569 dwArg08, Register out ptr32 edxOut, Register out (ptr Eq_1698) ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
word32 fn1000BA48(Eq_4 * edx, Eq_4 * ebx, Eq_6 * es, Eq_7 * ds, HMODULE dwArg04, HANDLE dwArg08, ptr32 & edxOut, Eq_1698 * & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	*edxOut = edx;
	globals->t10024480 = dwArg04;
	word32 * esp_17 = fp - 0x0C;
	word32 esi_20 = 0x01;
	if (dwArg08 != null)
	{
		if (dwArg08 == (void *) 0x01)
		{
			fn10009330(dwArg04);
			esi_20 = fn1000D35B(edx, ebx, fp - 0x04, es, ds);
			esp_17 = fp - 0x0C;
		}
	}
	else
	{
		word32 edi_71;
		word32 ebp_72;
		word32 eax_73;
		word32 ecx_74;
		byte SZO_76;
		byte C_77;
		byte SCZO_78;
		byte Z_79;
		word32 edx_80;
		word32 ebx_81;
		struct Eq_3047 * es_82;
		struct Eq_3048 * ds_83;
		ntdll.dll!EtwEventUnregister();
		globals->dw10024020 = 0x00;
		globals->dw10024024 = 0x00;
		globals->dw10024008 = 0x00;
		word32 edx_87;
		*edxOut = fn10009510();
	}
	struct Eq_3066 * esp_38 = esp_17 + 0x01;
	word32 edi_37;
	*ediOut = *esp_17;
	word32 esi_40;
	*esiOut = esp_38->dw0000;
	word32 ebp_42;
	*ebpOut = esp_38->dw0004;
	return esi_20;
}

// 1000D35B: Register Eq_258 fn1000D35B(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register (ptr Eq_6) es, Register (ptr Eq_7) ds)
Eq_258 fn1000D35B(Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, Eq_6 * es, Eq_7 * ds)
{
	ui32 eax_11 = globals->dw100240C4 ^ fp - 0x04;
	globals->dw10024028 = globals->dw10024028 & 0x00;
	globals->dw1002402C = globals->dw1002402C & 0x00;
	word32 edi_54;
	byte SCZO_56;
	word32 eax_57;
	byte SZO_58;
	byte C_59;
	word32 esi_60;
	byte Z_61;
	word16 si_62;
	word32 ecx_63;
	struct Eq_7 * ds_130;
	struct Eq_6 * es_129;
	struct Eq_4 * ebx_128;
	struct Eq_4 * edx_127;
	struct Eq_5 * ebp_118;
	struct Eq_3131 * esp_116;
	ntdll.dll!EtwEventRegister();
	Eq_258 esi_123 = fp - 0x18;
	word16 si_69 = (word16) (fp - 0x18);
	if ((fp - 0x18 & fp - 0x18) != 0x00)
	{
		if ((fp - 0x18 & fp - 0x18) > 0x00)
			esi_123 = (word32) si_69 | 0x80070000;
	}
	else
	{
		word16 * ecx_102 = globals->ptr1002400C;
		word32 eax_103 = (word32) *ecx_102;
		*(esp_116 - 0x04) = eax_103;
		*(esp_116 - 0x08) = (word16 **) ecx_102;
		*(esp_116 - 0x0C) = 0x02;
		*(esp_116 - 0x10) = globals->dw10024024;
		*(esp_116 - 0x14) = globals->dw10024020;
		word32 edi_117;
		byte SCZO_119;
		word32 eax_120;
		byte SZO_121;
		byte C_122;
		byte Z_124;
		word16 si_125;
		word32 ecx_126;
		ntdll.dll!EtwEventSetInformation();
	}
	Eq_258 esi_90 = esp_116->t0004;
	fn1000A130(esi_123, eax_11 ^ fp - 0x04, edx_127, ebx_128, ebp_118, esi_90, esp_116->ptr0000, es_129, ds_130, ebp);
	return esi_90;
}

// 1000D51F: Register Eq_258 fn1000D51F(Register ptr32 ecx, Register (ptr Eq_4) edx, Register (ptr Eq_5) ebp, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack Eq_258 dwArg04, Stack (ptr Eq_4) dwArg08, Stack (ptr ui32) dwArg0C, Register out (ptr Eq_545) edxOut, Register out ptr32 esiOut)
Eq_258 fn1000D51F(ptr32 ecx, Eq_4 * edx, Eq_5 * ebp, Eq_6 * es, Eq_7 * ds, Eq_258 dwArg04, Eq_4 * dwArg08, ui32 * dwArg0C, Eq_545 * & edxOut, ptr32 & esiOut)
{
	ui32 eax_15 = globals->dw100240C4 ^ fp - 0x04;
	*dwArg0C = *dwArg0C & 0x00;
	word32 esp_37;
	word32 edi_38;
	word32 ebp_39;
	word32 ecx_40;
	word32 eax_41;
	byte SZO_42;
	byte C_43;
	word32 ebx_44;
	<anonymous> * esi_45;
	byte SCZO_46;
	byte Z_47;
	word32 edx_48;
	struct Eq_3238 * es_49;
	struct Eq_3239 * ds_50;
	globals->ptr10025410();
	ptr32 esp_51;
	word32 edi_52;
	word32 ebp_53;
	word32 ecx_54;
	word32 eax_55;
	byte SZO_56;
	byte C_57;
	word32 ebx_58;
	word32 esi_59;
	byte SCZO_60;
	byte Z_61;
	word32 edx_62;
	struct Eq_3254 * es_63;
	struct Eq_3255 * ds_64;
	esi_45();
	*(esp_51 - 0x04) = ebx_58;
	word32 esp_71;
	word32 edi_72;
	word32 ebp_73;
	word32 ecx_74;
	word32 eax_75;
	byte SZO_76;
	byte C_77;
	word32 ebx_78;
	<anonymous> * esi_79;
	byte SCZO_80;
	byte Z_81;
	word32 edx_82;
	struct Eq_3273 * es_83;
	struct Eq_3274 * ds_84;
	globals->ptr10025410();
	struct Eq_3277 * esp_85;
	struct Eq_5 * ebp_87;
	word32 ecx_88;
	word32 * eax_89;
	byte SZO_90;
	byte C_91;
	word32 ebx_92;
	word32 esi_93;
	byte SCZO_94;
	byte Z_95;
	struct Eq_6 * es_97;
	struct Eq_7 * ds_98;
	word32 * edi_102;
	struct Eq_4 * edx_101;
	esi_79();
	while (true)
	{
		Eq_258 eax_111;
		if (edi_102 >= eax_89)
			break;
		struct Eq_3293 * ecx_130 = *edi_102;
		if (ecx_130 != null)
		{
			*edxOut = dwArg04;
			if (fn1000D7C7(ecx_130->ptr0004, dwArg04) != 0x00)
			{
				*(esp_85 - 0x04) = dwArg0C;
				*(esp_85 - 0x08) = *edi_102;
				*(esp_85 - 0x0C) = (struct Eq_4 **) dwArg08;
				*edxOut = fp - 0x0C;
				eax_111 = fn1000D65C(ebx_92, fp - 0x0C, ebp_87, es_97, ds_98, dwArg00, dwArg04, dwArg08);
				goto l1000D583;
			}
		}
		edi_102 = edi_102 + 0x01;
	}
	eax_111 = 0x80040111;
l1000D583:
	Eq_258 esi_116 = esp_85->t0004;
	*esiOut = esi_116;
	return fn1000A130(eax_111, eax_15 ^ fp - 0x04, edx_101, esp_85->ptr0008, ebp_87, esi_116, esp_85->ptr0000, es_97, ds_98, ebp);
}

// 1000D5FD: Register word32 fn1000D5FD(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register Eq_258 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds)
word32 fn1000D5FD(Eq_4 * edx, Eq_4 * ebx, Eq_258 edi, Eq_6 * es, Eq_7 * ds)
{
	if (globals->dw10024618 > ((fs->ptr002C))[globals->dw1002444C]->dw0004)
	{
		fn1000B57D(edx, ebx, 0x1002461C, es, ds, &globals->dw10024618);
		if (globals->dw10024618 == ~0x00)
		{
			*(fp - 0x0C) = 0x1000CE00;
			globals->ptr10024484 = 0x1002461C;
			globals->ptr1002461C = 0x10001058;
			Eq_258 esi_52;
			struct Eq_4 * ebx_53 = fn1000A45E(edx, ebx, 0x10024618, 0x1002461C, es, ds, dwArg00, out esi_52);
			*(fp - 0x10) = (union Eq_258 *) esi_52;
			fn1000B53C(edx, ebx_53, ebp, esi_52, 0x1002461C, es, ds, dwArg00);
		}
		esi = *(fp - 0x08);
	}
	return esi;
}

// 1000D65C: Register Eq_258 fn1000D65C(Register word32 ecx, Register (ptr byte) edx, Register (ptr Eq_5) ebp, Register (ptr Eq_6) es, Register (ptr Eq_7) ds, Stack word32 dwArg04, Stack Eq_258 dwArg08, Stack (ptr Eq_4) dwArg0C)
Eq_258 fn1000D65C(word32 ecx, byte * edx, Eq_5 * ebp, Eq_6 * es, Eq_7 * ds, word32 dwArg04, Eq_258 dwArg08, Eq_4 * dwArg0C)
{
	struct Eq_5 * ebp_101;
	struct Eq_4 * edx_108;
	struct Eq_6 * es_112;
	struct Eq_7 * ds_113;
	ptr32 * esp_133;
	Eq_258 eax_103;
	ui32 eax_11 = globals->dw100240C4 ^ fp - 0x04;
	dwArg0C->dw0000 = 0x00;
	ptr32 esp_23 = fp - 0x20;
	if (**((word32) dwArg08 + 0x0C) != 0x00)
	{
		word32 esp_348;
		word32 edi_349;
		word32 ebp_350;
		byte SCZO_351;
		word32 eax_352;
		byte SZO_353;
		byte C_354;
		word32 ebx_355;
		<anonymous> * esi_356;
		word32 edx_357;
		word32 ecx_358;
		byte Z_359;
		byte S_360;
		struct Eq_3513 * es_361;
		struct Eq_3514 * ds_362;
		globals->ptr10025410();
		ptr32 esp_363;
		word32 edi_364;
		word32 ebp_365;
		byte SCZO_366;
		word32 eax_367;
		byte SZO_368;
		byte C_369;
		word32 ebx_370;
		word32 esi_371;
		word32 edx_372;
		word32 ecx_373;
		byte Z_374;
		byte S_375;
		struct Eq_3530 * es_376;
		struct Eq_3531 * ds_377;
		esi_356();
		*(esp_363 - 0x04) = eax_367;
		AcquireSRWLockShared(*(esp_363 - 0x04));
		esp_23 = esp_363;
		word32 * ecx_383 = *((word32) dwArg08 + 0x0C);
		if (*ecx_383 != 0x00)
		{
			*(esp_363 - 0x04) = *ecx_383;
			Eq_330 eax_389 = DecodePointer(*(esp_363 - 0x04));
			*(esp_363 - 0x04) = (struct Eq_4 **) dwArg0C;
			*(esp_363 - 0x08) = dwArg04;
			*(esp_363 - 0x0C) = (PVOID *) eax_389;
			word32 esp_403;
			word32 edi_404;
			word32 ebp_405;
			byte SCZO_406;
			word32 eax_407;
			byte SZO_408;
			byte C_409;
			word32 ebx_410;
			<anonymous> * esi_411;
			word32 edx_412;
			word32 ecx_413;
			byte Z_414;
			byte S_415;
			struct Eq_3599 * es_416;
			struct Eq_3600 * ds_417;
			globals->ptr10025410();
			ptr32 * esp_418;
			word32 edi_419;
			byte SCZO_421;
			Eq_258 eax_422;
			byte SZO_423;
			byte C_424;
			word32 ebx_425;
			word32 esi_426;
			word32 ecx_428;
			byte Z_429;
			byte S_430;
			esi_411();
			if (ebx_425 != 0x00)
			{
				*(esp_418 - 0x04) = ebx_425;
				ReleaseSRWLockShared(*(esp_418 - 0x04));
			}
			esp_133 = esp_418;
			eax_103 = eax_422;
l1000D7B4:
			struct Eq_3629 * esp_50 = esp_133 + 0x01;
			return fn1000A130(eax_103, eax_11 ^ fp - 0x04, edx_108, esp_50->ptr0004, ebp_101, esp_50->t0000, *esp_133, es_112, ds_113, ebp);
		}
		if (eax_367 != 0x00)
		{
			*(esp_363 - 0x04) = eax_367;
			ReleaseSRWLockShared(*(esp_363 - 0x04));
			esp_23 = esp_363;
		}
	}
	ptr32 * esp_67 = esp_23 - 0x04;
	*esp_67 = fp - 0x0C;
	*(esp_67 - 0x04) = dwArg04;
	*(esp_67 - 0x08) = (union Eq_258 *) dwArg08;
	*(esp_67 - 0x0C) = (byte **) edx;
	word32 esp_84;
	word32 edi_85;
	word32 ebp_86;
	byte SCZO_87;
	word32 eax_88;
	byte SZO_89;
	byte C_90;
	word32 ebx_91;
	<anonymous> * esi_92;
	word32 edx_93;
	word32 ecx_94;
	byte Z_95;
	byte S_96;
	struct Eq_3485 * es_97;
	struct Eq_3486 * ds_98;
	globals->ptr10025410();
	word32 edi_100;
	byte SCZO_102;
	byte SZO_104;
	byte C_105;
	word32 ebx_106;
	word32 esi_107;
	word32 ecx_109;
	byte Z_110;
	byte S_111;
	esi_92();
	if (eax_103 < 0x00)
		goto l1000D7B4;
	word32 edi_128;
	if ((*edx & 0x04) == 0x00)
	{
		ptr32 * esp_212;
		*(esp_133 - 0x04) = ecx;
		word32 esp_161;
		word32 edi_162;
		word32 ebp_163;
		byte SCZO_164;
		word32 eax_165;
		byte SZO_166;
		byte C_167;
		word32 ebx_168;
		<anonymous> * esi_169;
		word32 edx_170;
		word32 ecx_171;
		byte Z_172;
		byte S_173;
		struct Eq_3673 * es_174;
		struct Eq_3674 * ds_175;
		globals->ptr10025410();
		ptr32 * esp_176;
		byte SCZO_179;
		Eq_199 eax_180;
		byte SZO_181;
		byte C_182;
		struct Eq_3682 * ebx_183;
		word32 esi_184;
		word32 ecx_186;
		byte Z_187;
		byte S_188;
		word32 edi_177;
		esi_169();
		*(esp_176 - 0x04) = (PSRWLOCK *) eax_180;
		AcquireSRWLockExclusive(*(esp_176 - 0x04));
		Eq_330 eax_197 = *ebx_183->ptr000C;
		if (eax_197 == null)
		{
			*(esp_176 - 0x04) = 0x00;
			*ebx_183->ptr000C = (PVOID *) EncodePointer(*(esp_176 - 0x04));
			esp_212 = esp_176;
		}
		else
		{
			*(esp_176 - 0x04) = (PVOID *) eax_197;
			Eq_330 eax_304 = DecodePointer(*(esp_176 - 0x04));
			*(esp_176 - 0x04) = (PVOID *) eax_304;
			word32 esp_312;
			word32 edi_313;
			word32 ebp_314;
			byte SCZO_315;
			word32 eax_316;
			byte SZO_317;
			byte C_318;
			word32 ebx_319;
			<anonymous> * esi_320;
			word32 edx_321;
			word32 ecx_322;
			byte Z_323;
			byte S_324;
			struct Eq_3738 * es_325;
			struct Eq_3739 * ds_326;
			globals->ptr10025410();
			byte SCZO_330;
			word32 eax_331;
			byte SZO_332;
			byte C_333;
			word32 ebx_334;
			word32 esi_335;
			word32 ecx_337;
			byte Z_338;
			byte S_339;
			esi_320();
		}
		if (eax_180 != null)
		{
			PSRWLOCK * esp_292 = esp_212 - 0x04;
			*esp_292 = (PSRWLOCK *) eax_180;
			ReleaseSRWLockExclusive(*esp_292);
		}
		esp_133 = esp_212;
		if (edi_177 != 0x00)
		{
			word32 * esp_221 = esp_212 - 0x04;
			*esp_221 = 0x00;
			word32 esp_226;
			word32 edi_227;
			word32 ebp_228;
			byte SCZO_229;
			word32 eax_230;
			byte SZO_231;
			byte C_232;
			word32 ebx_233;
			<anonymous> * esi_234;
			word32 edx_235;
			word32 ecx_236;
			byte Z_237;
			byte S_238;
			struct Eq_3806 * es_239;
			struct Eq_3807 * ds_240;
			globals->ptr10025410();
			ptr32 esp_241;
			word32 edi_242;
			word32 ebp_243;
			byte SCZO_244;
			word32 eax_245;
			byte SZO_246;
			byte C_247;
			word32 ebx_248;
			word32 esi_249;
			word32 edx_250;
			word32 ecx_251;
			byte Z_252;
			byte S_253;
			struct Eq_3823 * es_254;
			struct Eq_3824 * ds_255;
			esi_234();
			*(esp_241 - 0x04) = 0x00;
			word32 esp_262;
			word32 edi_263;
			word32 ebp_264;
			byte SCZO_265;
			word32 eax_266;
			byte SZO_267;
			byte C_268;
			word32 ebx_269;
			<anonymous> * esi_270;
			word32 edx_271;
			word32 ecx_272;
			byte Z_273;
			byte S_274;
			struct Eq_3844 * es_275;
			struct Eq_3845 * ds_276;
			globals->ptr10025410();
			byte SCZO_280;
			word32 eax_281;
			byte SZO_282;
			byte C_283;
			word32 ebx_284;
			word32 esi_285;
			word32 ecx_287;
			byte Z_288;
			byte S_289;
			esi_270();
l1000D7AD:
			dwArg0C->dw0000 = edi_128;
			eax_103 = 0x00;
			goto l1000D7B4;
		}
	}
	edi_128 = 0x00;
	goto l1000D7AD;
}

// 1000D7C7: Register word32 fn1000D7C7(Register (ptr void) ecx, Register Eq_258 edx)
word32 fn1000D7C7(void, Eq_258 edx)
{
	return (word32) (memcmp(ecx, edx, 0x10) == 0x00);
}

// 1000D8B0: void DllGetActivationFactory(Register (ptr Eq_4) edx, Register (ptr Eq_4) ebx, Register (ptr Eq_5) ebp, Register Eq_258 edi, Register (ptr Eq_6) es, Register (ptr Eq_7) ds)
void DllGetActivationFactory(Eq_4 * edx, Eq_4 * ebx, Eq_5 * ebp, Eq_258 edi, Eq_6 * es, Eq_7 * ds)
{
	word32 esi_12 = fn1000D5FD(edx, ebx, edi, es, ds);
	word32 ebp_15 = *(fp - 0x04);
	ptr32 * esp_134;
	struct Eq_5 * ebp_136;
	Eq_258 esi_143;
	struct Eq_4 * edx_147;
	struct Eq_6 * es_148;
	struct Eq_7 * ds_149;
	Eq_258 eax_401;
	*(fp - 0x04) = ebp_15;
	*(fp - 0x08) = globals->dw100240C4 ^ fp - 0x04;
	ui32 * eax_25 = fp->ptr0008;
	*(fp - 0x44) = (struct Eq_4 **) ebx;
	*(fp - 0x48) = esi_12;
	word32 esi_30 = fp->dw0004;
	*eax_25 = *eax_25 & 0x00;
	*(fp - 0x4C) = (union Eq_258 *) edi;
	*(fp - 0x50) = esi_30;
	*(fp - 0x40) = eax_25;
	word32 edi_42;
	word32 ecx_44;
	word32 eax_45;
	byte SCZO_46;
	byte SZO_47;
	byte C_48;
	word32 ebx_49;
	word32 esi_50;
	byte Z_51;
	byte S_52;
	word16 dx_53;
	word32 edx_54;
	struct Eq_3973 * es_55;
	struct Eq_3974 * ds_56;
	ptr32 ebp_110;
	ptr32 esp_111;
	api-ms-win-core-winrt-string-l1-1-0.dll!WindowsIsStringEmpty();
	if (eax_45 == 0x00)
	{
		*(esp_111 - 0x04) = ebp_110 - 0x34;
		*(esp_111 - 0x08) = esi_50;
		word32 edi_156;
		word32 ecx_158;
		int32 eax_159;
		byte SCZO_160;
		byte SZO_161;
		byte C_162;
		word32 ebx_163;
		word32 esi_164;
		byte Z_165;
		byte S_166;
		word16 dx_167;
		word32 edx_168;
		struct Eq_4026 * es_169;
		struct Eq_4027 * ds_170;
		api-ms-win-core-winrt-string-l1-1-0.dll!WindowsStringHasEmbeddedNull();
		if (eax_159 >= 0x00 && *(ebp_110 - 0x34) != 0x01)
		{
			*(esp_111 - 0x04) = 0x00;
			*(esp_111 - 0x08) = esi_164;
			ptr32 esp_180;
			word32 edi_181;
			ptr32 ebp_182;
			word32 ecx_183;
			word32 eax_184;
			byte SCZO_185;
			byte SZO_186;
			byte C_187;
			word32 ebx_188;
			word32 esi_189;
			byte Z_190;
			byte S_191;
			word16 dx_192;
			word32 edx_193;
			struct Eq_4063 * es_194;
			struct Eq_4064 * ds_195;
			api-ms-win-core-winrt-string-l1-1-0.dll!WindowsGetStringRawBuffer();
			*(esp_180 - 0x04) = ebx_188;
			*(ebp_182 - 0x38) = eax_184;
			word32 esp_202;
			word32 edi_203;
			word32 ebp_204;
			word32 ecx_205;
			word32 eax_206;
			byte SCZO_207;
			byte SZO_208;
			byte C_209;
			word32 ebx_210;
			<anonymous> * esi_211;
			byte Z_212;
			byte S_213;
			word16 dx_214;
			word32 edx_215;
			struct Eq_4090 * es_216;
			struct Eq_4091 * ds_217;
			globals->ptr10025410();
			ptr32 esp_218;
			word32 edi_219;
			word32 ebp_220;
			word32 ecx_221;
			word32 eax_222;
			byte SCZO_223;
			byte SZO_224;
			byte C_225;
			word32 ebx_226;
			word32 esi_227;
			byte Z_228;
			byte S_229;
			word16 dx_230;
			word32 edx_231;
			struct Eq_4108 * es_232;
			struct Eq_4109 * ds_233;
			esi_211();
			*(esp_218 - 0x04) = ebx_226;
			word32 esp_240;
			word32 edi_241;
			word32 ebp_242;
			word32 ecx_243;
			word32 eax_244;
			byte SCZO_245;
			byte SZO_246;
			byte C_247;
			word32 ebx_248;
			<anonymous> * esi_249;
			byte Z_250;
			byte S_251;
			word16 dx_252;
			word32 edx_253;
			struct Eq_4129 * es_254;
			struct Eq_4130 * ds_255;
			globals->ptr10025410();
			ptr32 ebp_258;
			word32 ecx_259;
			byte SCZO_261;
			byte SZO_262;
			byte C_263;
			word32 ebx_264;
			word32 esi_265;
			byte Z_266;
			byte S_267;
			word16 dx_268;
			word32 edx_269;
			struct Eq_4144 * es_270;
			struct Eq_4145 * ds_271;
			word32 * edi_257;
			word32 * eax_260;
			ptr32 * esp_256;
			esi_249();
			*(ebp_258 - 0x30) = eax_260;
			if (edi_257 >= eax_260)
			{
				word32 * esp_289 = esp_256 - 0x04;
				*esp_289 = 0x00;
				*(esp_289 - 0x04) = 0x80040111;
				word32 edi_295;
				word32 ecx_297;
				word32 eax_298;
				byte SCZO_299;
				byte SZO_300;
				byte C_301;
				word32 ebx_302;
				byte Z_304;
				byte S_305;
				word16 dx_306;
				api-ms-win-core-winrt-error-l1-1-0.dll!RoOriginateError();
				goto l1000D50A;
			}
			if (*edi_257 == 0x00)
			{
l1000D4B7:
				edi_257 = edi_257 + 0x01;
				goto l1000D4BA;
			}
			else
			{
				word32 esp_333;
				word32 edi_334;
				word32 ebp_335;
				word32 ecx_336;
				word32 eax_337;
				byte SCZO_338;
				byte SZO_339;
				byte C_340;
				word32 ebx_341;
				<anonymous> * esi_342;
				byte Z_343;
				byte S_344;
				word16 dx_345;
				word32 edx_346;
				struct Eq_4237 * es_347;
				struct Eq_4238 * ds_348;
				globals->ptr10025410();
				word32 ecx_352;
				byte SCZO_354;
				byte SZO_355;
				byte C_356;
				word32 ebx_357;
				word32 esi_358;
				byte Z_359;
				byte S_360;
				word16 dx_361;
				word32 edx_362;
				struct Eq_4251 * eax_353;
				esi_342();
				struct Eq_4252 * ecx_365 = *(ebp_136 - 0x38) + 0x02;
l1000D485:
				ui32 eax_381;
				word16 dx_369 = ecx_365->w0000;
				Eq_4261 C_374 = cond(dx_369 - eax_353->w0000);
				if (dx_369 == eax_353->w0000)
				{
					if (dx_369 == 0x00)
						break;
					word16 dx_425 = ecx_365->w0000;
					C_374 = cond(dx_425 - eax_353->w0002);
					if (dx_425 == eax_353->w0002)
					{
						ecx_365 = ecx_365 + 0x01;
						eax_353 = eax_353 + 0x01;
						if (dx_425 != 0x00)
							goto l1000D485;
						eax_381 = 0x00;
						if (eax_381 == 0x00)
						{
							*(esp_256 - 0x04) = *(ebp_136 - 0x3C);
							*(ebp_136 - 0x30) = 0x01;
							*(esp_256 - 0x08) = *edi_257;
							*(esp_256 - 0x0C) = 0x100071CC;
							edx_147 = ebp_136 - 0x30;
							eax_401 = fn1000D65C(ebx_357, ebp_136 - 0x30, ebp_136, es_148, ds_149, dwArg00, dwArg04, dwArg08);
							esp_134 = esp_256;
							goto l1000D50C;
						}
						eax_260 = *(ebp_136 - 0x30);
						goto l1000D4B7;
					}
				}
				eax_381 = 0x00 - C_374 | 0x01;
				goto l1000D4B0;
			}
		}
	}
	word32 * esp_112 = esp_111 - 0x04;
	*esp_112 = 0x0A;
	word32 ecx_114 = *esp_112;
	word32 eax_116 = ebp_110 - 44;
	*esp_112 = eax_116;
	word32 * esi_117 = globals->a100071A4;
	word32 * edi_118 = ebp_110 - 44;
	while (ecx_114 != 0x00)
	{
		*edi_118 = *esi_117;
		esi_117 = esi_117 + 0x01;
		edi_118 = edi_118 + 0x01;
		ecx_114 = ecx_114 - 0x01;
	}
	*(esp_112 - 0x04) = 0x13;
	*(esp_112 - 0x08) = 0x80070057;
	word32 edi_135;
	word32 ecx_137;
	word32 eax_138;
	byte SCZO_139;
	byte SZO_140;
	byte C_141;
	word32 ebx_142;
	byte Z_144;
	byte S_145;
	word16 dx_146;
	api-ms-win-core-winrt-error-l1-1-0.dll!RoOriginateErrorW();
l1000D50A:
	eax_401 = esi_143;
l1000D50C:
	struct Eq_4345 * esp_72 = esp_134 + 0x01;
	fn1000A130(eax_401, *(ebp_136 - 0x04) ^ ebp_136, edx_147, esp_72->ptr0004, ebp_136, esp_72->t0000, *esp_134, es_148, ds_149, ebp);
	return;
}

