cpp_quote("#include <winapifamily.h>")

#pragma region Desktop Family
cpp_quote("#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)")

import "./credentialprovider_10.idl";

enum CREDENTIAL_PROVIDER_DISPLAY_STATE_FLAGS
{
    CPDSF_NONE = 0x00000000,                //Default initialization value.
    CPDSF_AWAKE = 0x00000001,               //Is set when display is on (can be used for power-saving.)
    CPDSF_UNKNOWN_1 = 0x00000002,           //Transitive flag. It is mostly absent. It only appears before/after CPDSF_AWAKE changes.
    CPDSF_CURTAIN = 0x00000004,             //Is set when the "curtain" is pulled down, or obscures the tiles.
    CPDSF_CURTAIN_MOVING = 0x00000008,      //Is set when the "curtain" is moving. It appears when the "curtain" is being pulled.
    CPDSF_STATION_LOCKED = 0x00000040,      //Is set when the workstation is locked.
    CPDSF_PROVIDER_VISIBLE = 0x00000080,    //Is set when provider screen is active/visible.
    CPDSF_NO_LOGGED_USERS = 0x00000400,     //Is set when there is no logged in users.
    CPDSF_UNKNOWN_2 = 0x00000800,           //Some unknown flag that is used by the PIN (NGC) provider.
    CPDSF_SHUTDOWN_STARTED = 0x00001000,    //Is set when reboot or shutdown had started.
    CPDSF_ACTIVE = 0x00010000,              //Is set to indicate display activity. Is reset after some time when UI is idle.
    CPDSF_TBAL_LOGON = 0x00080000           //Is set for the trusted boot auto-logon (TBAL) boot.
};

// A "curtain" is when the LogonUI.exe hides all credential tiles after a period of inactivity,
// or right after it is initially shown. This appears to be a security feature.
//
MIDL_INTERFACE("A09BCC29-D779-4513-BB59-B4DB5D82D2B6")
interface ICredentialProviderWithDisplayState : public IUnknown
{
    HRESULT STDMETHODCALLTYPE SetDisplayState(__in CREDENTIAL_PROVIDER_DISPLAY_STATE_FLAGS Flags);
};

MIDL_INTERFACE("4a54a3b6-a8d3-46a8-9080-811ba8ccb07d")
interface ICredentialProviderCredential4 : ICredentialProviderCredential3
{
    HRESULT STDMETHODCALLTYPE GetTextFieldMaxLength(__in DWORD dwFieldID, __out DWORD * pMaxLength);
};

MIDL_INTERFACE("1ecf61d8-745e-4484-bcc7-182cea64c787")
interface ICredentialProviderCredential5 : ICredentialProviderCredential4
{
    HRESULT STDMETHODCALLTYPE GetAccessibilityTextForField(_In_ DWORD dwFieldID, _Out_ PWSTR* ppszText);
    HRESULT STDMETHODCALLTYPE GetIsAccessibilityViewRawForField(_In_ DWORD dwFieldID, _Out_ BOOL* pbRaw);
};

MIDL_INTERFACE("F6247CF9-061D-46E7-AAA7-0FDE071A5C1A")
interface ICredentialProviderCredentialTileDataInfo : public IUnknown
{
    HRESULT STDMETHODCALLTYPE SetTileVisibility(__in BOOL bVisibile);
    HRESULT STDMETHODCALLTYPE GetTileVisibility(__out PBOOL pbVisibile);
};

interface IAutoLogonManager : public IUnknown 
{
    HRESULT STDMETHODCALLTYPE IgnoreAutoLogonMode();
    BOOL STDMETHODCALLTYPE IsAutoLogonMode();
    BOOL STDMETHODCALLTYPE IsSingleUserNoPasswordAutoLogonMode();
    BOOL STDMETHODCALLTYPE IsAutoLogonNotSingleUserNoPasswordMode();
    BOOL STDMETHODCALLTYPE IsSystemAutoLogon();
    HRESULT STDMETHODCALLTYPE UpdateAutoLogonDefaultSID();
    HRESULT STDMETHODCALLTYPE ResetAutoLogonSetting();
    HRESULT STDMETHODCALLTYPE ClearSystemAutoLogonSetting();
    HRESULT STDMETHODCALLTYPE GetAutoLogonCredential(_Out_ PWSTR*, _Out_ PWSTR*, _Out_ PWSTR*);
    BOOL STDMETHODCALLTYPE IsSingleUser();
    HRESULT STDMETHODCALLTYPE GetSerializedAutoLogonCredential(ICredProviderCredentialSerialization * *);
};

MIDL_INTERFACE("8A4E89FE-C09D-475E-88CB-F8F11E047C50")
interface IAutoLogonProvider : public IUnknown 
{
    HRESULT STDMETHODCALLTYPE SetAutoLogonManager(IAutoLogonManager *pAutoLogonManager);
};


MIDL_INTERFACE("DF50EA86-B7A9-4485-8F04-930A49686E5B")
ICredentialProviderCredentialEvents4 : public ICredentialProviderCredentialEvents3
{
    HRESULT STDMETHODCALLTYPE RequestSerialization();
    HRESULT STDMETHODCALLTYPE RequestSelection();
};	

MIDL_INTERFACE("c4a56475-d6f5-43e3-80ae-1aa99833cc05")
ICredentialProviderCredentialEvents5 : public ICredentialProviderCredentialEvents4
{
    HRESULT STDMETHODCALLTYPE SetTextFieldMaxLength(
        _In_ ICredentialProviderCredential * pcpc, _In_ DWORD dwFieldID, _In_ DWORD MaxLength);

    HRESULT STDMETHODCALLTYPE SetAccessibilityTextForField(
        _In_ ICredentialProviderCredential *pcpc, _In_ DWORD dwFieldID, _In_ PCWSTR pcszText);

    HRESULT STDMETHODCALLTYPE SetRawAccessibilityViewForField(
        _In_ ICredentialProviderCredential *pcpc, _In_ DWORD dwFieldID, _In_ BOOL bRaw);

    HRESULT STDMETHODCALLTYPE RequestWebDialogVisibilityChange(
        _In_ ICredentialProviderCredential *pcpc, _In_ BOOL bVisible);
};

// {0b7b0ad8-cc36-4d59-802b-82f714fa7022}
DEFINE_GUID(CPFG_STANDALONE_SUBMIT_BUTTON, 0x0b7b0ad8, 0xcc36, 0x4d59, 0x80, 0x2b, 0x82, 0xf7, 0x14, 0xfa, 0x70, 0x22);

cpp_quote("#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */")
#pragma endregion
